// ESLint flat config for the whole monorepo.
//
// WHY THIS EXISTS. Ten `// eslint-disable-next-line` comments were sitting in the
// source — seven in src/App.tsx, one in src/components/StatTiles.tsx, two in
// src/services/lemivSweep.test.ts — with NO ESLint installed anywhere in the repo.
// They read as deliberate, reviewed overrides of rules that no tool would ever
// apply. The eight react-hooks/exhaustive-deps ones sit over an app with 111
// non-test hook call sites (42 useEffect, 49 useMemo, 19 useCallback, 1
// useLayoutEffect); the failure they invite is a new effect that copies a
// neighbour's `[physicsKey]` dep array, keeps a stale `launch` closure, and quietly
// simulates the PREVIOUS pad conditions while looking reviewed.
//
// WHY THE RULE SET IS SMALL. `npm run lint` is a deploy gate here — a push to main
// IS the production deploy — and a config that prints hundreds of errors on day one
// gets switched off. Everything below was run against this tree before being turned
// on, and every deviation from the recommended sets names the sites that forced it.
//
// Deliberately NOT enabled, with the measured reason:
//   - type-aware typescript-eslint configs: they need a full program build.
//     MEASURED 2026-09-22 (parserOptions.projectService): 12.6 s against 4.9 s,
//     +7.6 s on this tree — a cost to weigh, not a bar; the rules it would unlock
//     have simply not been adopted yet
//   - @typescript-eslint/no-non-null-assertion: 4,120 hits (624 outside tests) on
//     2026-09-23, load-bearing under the base tsconfig's noUncheckedIndexedAccess. The
//     figure read "~284" until 2026-09-08, which was 10x low — a reader sizing the
//     cleanup off it would have budgeted an afternoon for a week — and 2,902 until
//     2026-09-23. It only grows; re-measure before acting on it:
//     npx eslint . --rule '{"@typescript-eslint/no-non-null-assertion":"error"}'
//   - the React-Compiler rules shipped in eslint-plugin-react-hooks v6/v7
//     (set-state-in-effect, purity, immutability, …): only rules-of-hooks and
//     exhaustive-deps are wired up, because those are the two the source already
//     writes suppression comments for
//   - react-refresh/only-export-components: 10 of 35 .tsx modules deliberately export
//     both a component and its helpers so the helpers can be unit-tested
//
// The file extension is .mjs because the root package.json has no "type": "module".

import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';

export default tseslint.config(
  {
    // A suppression that suppresses nothing reads to a reviewer as a decision
    // that was made, and 5 of the 13 in this tree had already rotted into that
    // by 2026-09-08 — the config exists BECAUSE ten disables sat honouring no
    // linter for months. Flat config defaults this to 'warn'; as an error the
    // count cannot climb again. The five stale ones were deleted in the same
    // commit that turned this on.
    linterOptions: { reportUnusedDisableDirectives: 'error' },
  },
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      'packages/engine/vendor/**', // TeaVM-compiled kernel artifact — generated, never hand-edited
      'packages/app/src/data/userGuide.ts', // generated by scripts/build-user-guide.mjs from user-guide.md
      'engine-java/**', // Java kernel and its own build scripts; carved sources are never edited
      'validation/**', // published-data harness, run by hand, not part of any gate
      '**/*.d.ts',
      '**/*.d.mts', // else triple-slash/no-undef noise on src/vite-env.d.ts and scripts/manufacturers.d.mts
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    // Unused declarations, everywhere, one rule. The base rule is off because the
    // typescript-eslint one is the only one that understands `import type` — the live
    // example is tree/treeModel.ts's type-only import of ComponentType. `^_` opt-outs
    // match the convention already in the source (15 underscore-prefixed params).
    // ignoreRestSiblings is explicit rather than left to the default, which flipped to
    // false somewhere in typescript-eslint 8: `const { id, children, ...rest } = node`
    // is the omit idiom this codebase strips ids with (services/orkFile.test.ts's
    // stripIds; scripts/manufacturers.test.mjs's "did not silently collapse two
    // different parts" check), and naming a field in order to DROP it is a
    // use of that name, not dead code.
    rules: {
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrors: 'none',
        ignoreRestSiblings: true,
      }],
    },
  },

  {
    // ─── Four rules from the recommended sets, retuned against measured sites ───
    //
    // These fire ONLY on code that is deliberate here. Each is documented rather than
    // silently dropped so the next person can see what was checked.
    rules: {
      // 3 hits, all the same thing: a literal U+FEFF inside a regex that strips a BOM
      // from imported file text (the three readers: orkFile.ts importOrk,
      // rasaeroFile.ts importCdx1, rocksimFile.ts importRkt). skipRegExps keeps the
      // rule's real value — a stray non-breaking space in code — without outlawing the
      // character we exist to remove.
      'no-irregular-whitespace': ['error', { skipRegExps: true }],

      // 2 hits (prefs/PrefsContext.tsx's `ok` in the preference writer,
      // services/saveFile.ts's `handle` in saveFile), both the same shape: a defensive
      // initialiser before a try/catch that assigns in both branches. Removing the
      // initialiser is what the rule asks for and is strictly worse — `let handle:
      // FsFileHandle | null = null` is the declaration that gives the variable its type.
      'no-useless-assignment': 'off',

      // 4 hits, each matching a control character on purpose: three in
      // scripts/build-user-guide.mjs's inline(), which uses \x00 and \x01 as
      // sentinels while splitting the user guide, and services/textFold.ts's BREAKS,
      // which folds the \x1c-\x1e separators Python's splitlines() reads as line ends.
      'no-control-regex': 'off',

      // 2 hits (shareLink.ts decodeShareFragment, thrustcurve.ts fetchMotorSpec), both
      // deliberate: Chromium reports a corrupt deflate stream and a stalled body read
      // with messages that name the wrong condition, so the rethrow replaces them.
      // Attaching `cause` there would still be an improvement, so this stays visible
      // as a warning rather than being switched off.
      'preserve-caught-error': 'warn',

      // 4 hits, and 3 are one member of a group of siblings declared together where the
      // others ARE reassigned: tree/solidMesh.ts extrudePolygon's `a` (beside b and c,
      // which the winding-order swap reassigns) and tree/finOutline.ts relativeCcw's
      // dx2/dy2 (beside dpx/dpy/ccw, in a line-for-line transcription of
      // java.awt.geom.Line2D.relativeCCW that is meant to diff against its Java
      // source). Splitting such a group by which member a later branch happens to touch
      // reads worse than the uniform `let`. The fourth is a test's `open`
      // (components/useDialog.test.tsx).
      'prefer-const': 'off',
    },
  },

  {
    // ─── Browser-shipped source ───
    // globals.browser only: a bare `process` or `require` reaching this bundle is a
    // runtime crash for a user, not a lint nit.
    files: ['packages/*/src/**/*.{ts,tsx}'],
    languageOptions: {
      globals: { ...globals.browser },
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    plugins: { 'react-hooks': reactHooks },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      // WARN, not error: deliberate suppressions exist and each carries a written
      // reason — eight when this was written, twenty on 2026-09-23 (17 in App.tsx, 2 in
      // components/NozzleField.tsx, 1 in hooks/useRelaunchLatch.ts). As an error this
      // would have failed the deploy on day one or forced them to be rewritten blind. A
      // warning still puts a NEW stale dep array in the CI log, and deploy.yml's
      // --max-warnings ceiling makes it fail the deploy, which is the failure this
      // whole config is here to catch.
      'react-hooks/exhaustive-deps': 'warn',
      // The free half of the 2026-09-08 audit's recommendation: all three were
      // MEASURED at zero violations against this tree before being turned on, so
      // each costs nothing today and refuses the next instance. no-explicit-any
      // locks in a genuinely any-free codebase (zero `as any`, zero `: any` and
      // zero tsc-suppression comments, counted the same day). eqeqeq needs the
      // null:'ignore' option
      // to be free — all 105 loose comparisons here are the deliberate `== null`
      // idiom, and plain eqeqeq reports every one of them.
      '@typescript-eslint/no-explicit-any': 'error',
      'no-var': 'error',
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      // Thousands of non-null assertions, load-bearing under noUncheckedIndexedAccess.
      // The header carries the measured count and the command that re-measures it.
      '@typescript-eslint/no-non-null-assertion': 'off',
      // console.log in shipped code is a leak. warn/error survive because the app
      // reports engine failures through them, and debug because engine/kernelLogSink.ts:35
      // echoes the TeaVM kernel's stdout there behind an explicit opt-in flag.
      'no-console': ['error', { allow: ['warn', 'error', 'debug'] }],
    },
  },

  {
    // src/tree/ is the geometry layer — no file under it imports React (the one
    // "react" match, in tree/pieces.ts's header, is a comment about keeping
    // @react-three out of the entry bundle). The plugin reads ANY call to a function
    // named `use` as React's `use` hook, and tree/solidMesh.ts's isWatertight() calls
    // a local edge-counting helper called `use()` three times. Three false errors;
    // exhaustive-deps stays on, since it only fires on real hook calls.
    files: ['packages/app/src/tree/**'],
    rules: { 'react-hooks/rules-of-hooks': 'off' },
  },

  {
    // ─── Node-side build scripts and config ───
    // They legitimately read the disk and print progress.
    files: [
      'scripts/**/*.mjs',
      'packages/app/scripts/**/*.mjs',
      'eslint.config.mjs',
      '**/vite.config.ts',
    ],
    languageOptions: { globals: { ...globals.node } },
    rules: { 'no-console': 'off' },
  },

  {
    // packages/app/scripts/manufacturers.mjs is the ONE file in a directory of Node-only
    // build scripts that is ALSO imported by browser code (src/services/presets.ts and
    // src/services/recoverySizing.ts), so it ships inside the app bundle — `grep -c
    // semrocastronautics` finds it in the entry chunk. It is browser-safe today only
    // because it has zero imports, and 12 of its 14 sibling scripts import node:
    // builtins, so adding one here is the natural and wrong move. Nothing else would
    // catch it: vitest runs it under Node, tsc never reads the .mjs (it reads the
    // hand-written manufacturers.d.mts beside it), and vite would externalise node:fs
    // with a warning nobody reads in CI. The app would then throw on the first preset
    // match — the moment a user opens a .ork with a <PartMfg> in it.
    // manufacturers.browserSafe.test.mjs scans the source text for the same thing and
    // catches dynamic import() and require(), which this rule does not see.
    files: ['packages/app/scripts/manufacturers.mjs'],
    rules: {
      'no-restricted-imports': ['error', {
        patterns: [{
          group: ['node:*', 'fs', 'path', 'url', 'os', 'crypto', 'child_process'],
          message:
            'manufacturers.mjs is bundled into the browser app (imported by src/services/presets.ts '
            + 'and src/services/recoverySizing.ts). A node: import here deploys a module that throws '
            + 'on the first preset match. Put pipeline-only code in a sibling script instead.',
        }],
      }],
    },
  },

  {
    // Tests run under Node (vitest), some under happy-dom, and a few print measured
    // sweep numbers on purpose (services/lemivSweep.test.ts) — which is why
    // no-console is off here rather than suppressed line by line.
    files: ['**/*.test.{ts,tsx,mts,mjs,js}'],
    languageOptions: { globals: { ...globals.node, ...globals.browser } },
    rules: { 'no-console': 'off' },
  },
);
