import type { ComponentNode, ComponentType } from '@online-openrocket/engine';
import { csvCell } from './csvUtil.js';
// The ONE manufacturer alias table + part-number key, shared with the preset
// pipeline so the app matches a file's part the same way the database dedupes.
import { mfrKey, partKey } from '../../scripts/manufacturers.mjs';

/**
 * Component preset database (openrocket-database .orc files → presets.json,
 * regenerated by scripts/fetch-component-presets.mjs; all SI). The bundle is
 * ~1.3 MB so it loads lazily on first use. User presets imported from CSV
 * are stored in localStorage and merged in.
 */

export interface Preset {
  kind: string;
  manufacturer: string;
  partNo: string;
  description: string;
  material?: { name: string; type: string; density: number };
  lineMaterial?: { name: string; type: string; density: number };
  mass?: number;
  [dim: string]: unknown;
}

/** .orc kind → editor component type. */
export const KIND_FOR_TYPE: Partial<Record<ComponentType, string>> = {
  bodytube: 'BodyTube',
  // Inner tubes consume the BODY TUBE catalogue — desktop's own rule
  // (InnerTube.getPresetType() returns Type.BODY_TUBE; there is no InnerTube
  // preset kind in the .orc format at all). Until v0.089 this entry was
  // missing, so a motor-mount tube offered no preset picker whatsoever — and
  // the Composite Warehouse motor-mount tubes are exactly the rows a mount
  // wants.
  innertube: 'BodyTube',
  nosecone: 'NoseCone',
  transition: 'Transition',
  centeringring: 'CenteringRing',
  tubecoupler: 'TubeCoupler',
  bulkhead: 'BulkHead',
  engineblock: 'EngineBlock',
  launchlug: 'LaunchLug',
  parachute: 'Parachute',
  streamer: 'Streamer',
};

let bundled: Preset[] | null = null;

export async function loadPresets(): Promise<Preset[]> {
  if (!bundled) {
    const mod = await import('../data/presets.json');
    bundled = (mod.default as { presets: Preset[] }).presets;
  }
  return [...bundled, ...loadCustomPresets()];
}

const CUSTOM_KEY = 'online-openrocket.custom-presets.v1';

export function loadCustomPresets(): Preset[] {
  try {
    const raw = localStorage.getItem(CUSTOM_KEY);
    return raw ? (JSON.parse(raw) as Preset[]) : [];
  } catch {
    return [];
  }
}

export function saveCustomPresets(presets: Preset[]): void {
  try {
    localStorage.setItem(CUSTOM_KEY, JSON.stringify(presets));
  } catch {
    // Private browsing / quota — the presets still work for this session.
  }
}

const n = (p: Preset, key: string): number | undefined =>
  typeof p[key] === 'number' ? (p[key] as number) : undefined;

/**
 * Preset → node patch (editor params, SI). Desktop's semantics for dimensions
 * and material; a cataloged mass becomes a mass override on every part, where
 * desktop does that for a parachute only (real parts weigh what they weigh, not
 * what the geometry computes).
 *
 * THE PATCH DESCRIBES THE WHOLE PART, not only the fields the row happens to
 * carry (audit 2026-09-22). It is merged over the node (`updateNode` spreads
 * it), so a field the row lacks used to keep whatever the PREVIOUS part left
 * there — and trying one catalogue part and then another is ordinary. Measured
 * then: Fruity Chutes IFC-030-S followed by Apogee 29093 (no Cd, no vent) flew
 * the Fruity Chutes Cd 2.2 and its vent on the Apogee canopy, a flown Cd of
 * 2.09 where desktop flies the 0.8 default, so the rocket came down at 1.14 m/s
 * instead of 1.84 — the optimistic direction; and an Apogee 19490 thin-wall
 * nose applied after a solid cone stayed solid, 975.8 g instead of 86.5 g. So
 * every field this function OWNS is written either way: the row's value, or
 * `undefined`, which is how this app says "the default" (`updateNode` spreads
 * it over the old value, JSON drops it on the way to the kernel, and the kernel
 * applies its own default — the same one desktop's loadFromPreset resets to).
 * The mass override is the one exception, and has its own rule below: a user's
 * weighed mass is theirs, not the part's.
 *
 * `applyPresetLinks` below skips every undefined entry, so a catalogue link on
 * import still only ever FILLS what a file left unset; a clear here never
 * erases a value a file stated.
 */
export function presetPatch(
  type: ComponentType,
  p: Preset,
  /**
   * The part being replaced, and the catalogue it may have been picked from.
   * Only the mass override reads them, to tell a catalogue mass (the patch's to
   * clear) from a weight the user typed (never its to clear). The picker passes
   * both; without them nothing that might be the user's is cleared.
   */
  prior?: { node: ComponentNode; presets: readonly Preset[] },
): Partial<ComponentNode> {
  const patch: Partial<ComponentNode> = { name: `${p.manufacturer} ${p.partNo}` };
  const half = (v: number | undefined) => (v === undefined ? undefined : v / 2);
  const set = (key: string, v: unknown) => {
    if (v !== undefined && v !== null) (patch as Record<string, unknown>)[key] = v;
  };
  /** An owned field: the row's value, or back to the default when the row has none. */
  const own = (key: string, v: unknown) => {
    (patch as Record<string, unknown>)[key] = v === null ? undefined : v;
  };

  if (p.material?.type === 'BULK') {
    set('materialName', p.material.name);
    set('density', p.material.density);
  }
  // A catalogued mass of ZERO is not a part that weighs nothing, it is a row
  // that states no mass — and `overrideMass: 0` makes the component contribute
  // nothing at all while every other field still looks right, which on a nose
  // cone or a coupler moves the CG and the stability margin silently. No
  // shipped row carries mass 0 (measured over presets.json, 2026-09-04); the
  // guard is for the CSV import loop below, where a user can type one.
  //
  // WHAT A PICK DOES TO A MASS OVERRIDE (audit 2026-09-22, narrowed on review).
  // Desktop's loadFromPreset touches the mass on a PARACHUTE — the row's mass,
  // or back to computed (Parachute: massOverridden = false) — and on no other
  // part this picker serves, so a weight the user typed survives a change of
  // part. This app writes a catalogued mass as the override on EVERY part, so
  // it owes a clear of what it wrote, and nothing more:
  //  - a row with a mass writes it, and drops the subcomponents flag with it: a
  //    catalogue mass is one part's weight, never an assembly's. Left on, the
  //    flag made that weight the whole subtree's — a tube's fins, mount and
  //    everything under it together weighing the tube's 5.8 g;
  //  - a row with no mass clears the override (and flag, the pair the panel's
  //    Mass field clears together) where it is the PREVIOUS part's catalogue
  //    mass — else that part's weight rode onto this one — and on a parachute,
  //    as desktop does; a mass the user typed on any other part stays;
  //  - an assembly the user weighed (the flag on a mass that is not a
  //    catalogue mass) stays whole either way: one part changing inside it does
  //    not change what they weighed, and desktop keeps it too.
  const held = prior?.node['overrideMass'];
  const heldIsCatalogue = prior != null && holdsCatalogueMass(prior.node, prior.presets);
  const weighedAssembly = type !== 'parachute' && typeof held === 'number' && !heldIsCatalogue
    && prior?.node['overrideSubcomponentsMass'] === true;
  if (!weighedAssembly && p.mass !== undefined && p.mass > 0) {
    set('overrideMass', p.mass);
    own('overrideSubcomponentsMass', undefined);
  } else if (!weighedAssembly && (type === 'parachute' || heldIsCatalogue)) {
    own('overrideMass', undefined);
    own('overrideSubcomponentsMass', undefined);
  }
  // The catalogue identity rides with the part, so a saved .rkt names the row
  // it came from (<PartMfg>/<PartNo>) and an import can find it again.
  set('presetManufacturer', p.manufacturer);
  set('presetPartNo', p.partNo);

  const out = n(p, 'outsideDiameter');
  const inn = n(p, 'insideDiameter');
  /**
   * A row that names a shape brings that shape's DEFAULT parameter with it, and
   * (transitions) its default clipping — desktop's Transition.loadFromPreset
   * calls setShapeParameter(s.defaultParameter()) and setClipped(s.canClip).
   * Left alone, a 0.5 power-series parameter from the previous part rode onto
   * the catalogue's ogive, which reads it as a secant ogive: a different shape.
   * `undefined` is the kernel's own "setShapeType's default" (ComponentFactory).
   */
  const setShape = () => {
    if (typeof p['shape'] !== 'string') return;
    set('shape', (p['shape'] as string).toLowerCase());
    own('shapeParameter', undefined);
    if (type === 'transition') own('clipped', undefined);
  };
  switch (type) {
    case 'bodytube':
    case 'tubecoupler':
    case 'innertube':
      set('length', n(p, 'length'));
      set('outerRadius', half(out));
      if (out !== undefined && inn !== undefined) set('thickness', (out - inn) / 2);
      break;
    case 'nosecone':
      set('length', n(p, 'length'));
      set('aftRadius', half(out));
      setShape();
      // Solid or hollow is part of the part: a row that does not say solid
      // describes a hollow shell (every shipped nose row either says
      // `filled: true` or states a wall thickness, measured 2026-09-22, and
      // desktop's SymmetricComponent.loadFromPreset sets filled = false on a
      // THICKNESS). Writing only `true` left a solid cone's flag on the next,
      // hollow, part — the 975.8 g thin-wall nose above.
      own('filled', p['filled'] === true);
      set('shoulderRadius', half(n(p, 'shoulderDiameter')));
      set('shoulderLength', n(p, 'shoulderLength'));
      set('thickness', n(p, 'thickness'));
      break;
    case 'transition':
      set('length', n(p, 'length'));
      set('foreRadius', half(n(p, 'foreOutsideDiameter')));
      set('aftRadius', half(n(p, 'aftOutsideDiameter')));
      setShape();
      // A balsa reducer is solid. Until v0.097 only the nose-cone branch honoured
      // `filled`, so every one of the 314 catalogue transitions marked solid and
      // carrying no catalogue mass applied as a hollow 2 mm shell - measured
      // 1.129 g against 5.026 g on one SEMROC part, a 4.5x mass error. Ruled
      // 2026-09-03: "Fix it." And a hollow row writes `false`, for the reason
      // given on the nose-cone branch.
      own('filled', p['filled'] === true);
      set('foreShoulderRadius', half(n(p, 'foreShoulderDiameter')));
      set('foreShoulderLength', n(p, 'foreShoulderLength'));
      set('aftShoulderRadius', half(n(p, 'aftShoulderDiameter')));
      set('aftShoulderLength', n(p, 'aftShoulderLength'));
      set('thickness', n(p, 'thickness'));
      break;
    case 'centeringring':
    case 'bulkhead':
      set('length', n(p, 'length'));
      break;
    case 'engineblock':
      set('length', n(p, 'length'));
      // The catalogue OD is applied, exactly as the tubecoupler branch above
      // does and as desktop does: ThicknessRingComponent.loadFromPreset:21-36
      // sets outerRadiusAutomatic = false and outerRadius = OD/2 whenever the
      // row has an OUTER_DIAMETER. Without it a catalogue engine block took the
      // kernel's AUTOMATIC radius - the parent tube's inner radius - while the
      // very next line read the row's own outsideDiameter to compute the wall
      // and then threw the diameter away. That was invisible while the bridge
      // set the wall pre-attach, because the clamp made the part weigh 0 g
      // whatever its radius; now that the wall is real, the radius has to be
      // the catalogued one or a thrust ring reads its airframe's bore instead
      // of its own.
      set('outerRadius', half(out));
      if (out !== undefined && inn !== undefined) set('thickness', (out - inn) / 2);
      break;
    case 'launchlug':
      set('length', n(p, 'length'));
      set('outerRadius', half(out));
      if (out !== undefined && inn !== undefined) set('thickness', (out - inn) / 2);
      break;
    case 'parachute': {
      // Every canopy field below is OWNED — desktop's Parachute.loadFromPreset
      // resets each one the row lacks to its default (diameter, Cd → automatic
      // 0.8, line count 6, line length 0.3 m, both materials), and so does this.
      const pos = (v: number | undefined) => (v !== undefined && v > 0 ? v : undefined);
      own('diameter', pos(n(p, 'diameter')));
      // Manufacturer-rated canopy Cd (referenced to the nominal diameter).
      // Dropping this silently falls back to the kernel default 0.8 — a
      // Fruity Chutes Iris Ultra (Cd 2.2) then descends 1.66× too fast. A row
      // with no rated Cd (217 of 473, measured 2026-09-22) flies that default,
      // NOT the previous canopy's rating.
      own('cd', pos(n(p, 'dragCoefficient')));
      // A canopy's Cd and its spill hole are ONE fact. Fruity Chutes (and the
      // rest) quote a Cd referenced to the canopy area MINUS the vent; the
      // kernel works from the nominal diameter and scales by 1 − (d/D)², which
      // is the same area. Taking the Cd and dropping the hole reads 1.5–2 %
      // slow on every vented canopy — so they travel together, and a row with
      // no vent (188 rows carry a Cd and no vent) CLEARS the last canopy's, or
      // its Cd would be flown against somebody else's hole.
      own('spillHoleDiameter', n(p, 'spillHoleDiameter'));
      own('lineCount', pos(n(p, 'lineCount')));
      own('lineLength', pos(n(p, 'lineLength')));
      const surf = p.material?.type === 'SURFACE' ? p.material : undefined;
      own('surfaceMaterialName', surf?.name);
      own('surfaceDensity', surf?.density);
      own('lineMaterialName', p.lineMaterial?.name);
      own('lineDensity', p.lineMaterial?.density);
      break;
    }
    case 'streamer': {
      set('stripLength', n(p, 'length'));
      set('stripWidth', n(p, 'width'));
      // Owned like the canopy's: no rated Cd means the kernel's automatic
      // streamer Cd, which is what desktop's Streamer.loadFromPreset restores
      // (cdAutomatic = true) on every preset.
      const scd = n(p, 'dragCoefficient');
      own('cd', scd !== undefined && scd > 0 ? scd : undefined);
      const surf = p.material?.type === 'SURFACE' ? p.material : undefined;
      own('surfaceMaterialName', surf?.name);
      own('surfaceDensity', surf?.density);
      break;
    }
  }
  return patch;
}

// ---------------- CSV round-trip ----------------

/**
 * `bodytube` is not a kind. Every picker and the recovery sizer match kind by
 * exact string (`p.kind === 'Parachute'`), so a lower-case row imported, was
 * counted a success, and then appeared nowhere at all. Derived from
 * KIND_FOR_TYPE so there is one list of kinds and not two; an unrecognised
 * kind passes through as typed, exactly as before (2026-09-21).
 */
const CANONICAL_KIND = new Map(
  Object.values(KIND_FOR_TYPE).filter((k): k is string => !!k).map((k) => [k.toLowerCase(), k]),
);

/**
 * Measured over the shipped presets.json (2026-09-21): material type is a pure
 * function of kind — Parachute 473/473 and Streamer 67/67 SURFACE, and no row
 * outside those two kinds is SURFACE; of the other 4,190, 4,165 are BULK and 25
 * carry no material object at all (4,730 rows in all).
 *
 * So a blank materialType cell is filled from the KIND rather than assumed
 * BULK, which on a canopy threw the fabric weight away: `presetPatch` writes
 * `surfaceDensity` only for a SURFACE material, and the bulk `density` it
 * wrote instead reaches nothing — `ComponentFactory` applies a density only to
 * an External or Structural component and a Parachute is neither — so the
 * canopy arrived weightless rather than wrongly weighted.
 */
const SURFACE_KINDS = new Set(['Parachute', 'Streamer']);

const CSV_COLS = [
  'kind', 'manufacturer', 'partNo', 'description', 'materialName', 'materialType',
  'materialDensity', 'mass', 'length', 'outsideDiameter', 'insideDiameter', 'shape',
  'filled', 'shoulderDiameter', 'shoulderLength', 'thickness', 'foreOutsideDiameter',
  'aftOutsideDiameter', 'foreShoulderDiameter', 'foreShoulderLength',
  'aftShoulderDiameter', 'aftShoulderLength', 'diameter', 'dragCoefficient',
  'spillHoleDiameter', 'packedDiameter', 'packedLength', 'lineCount', 'lineLength', 'width',
  'lineMaterialName', 'lineMaterialDensity',
];

export function presetsToCsv(presets: Preset[]): string {
  const rows = [CSV_COLS.join(',')];
  for (const p of presets) {
    const flat: Record<string, unknown> = {
      ...p,
      materialName: p.material?.name,
      materialType: p.material?.type,
      materialDensity: p.material?.density,
      lineMaterialName: p.lineMaterial?.name,
      lineMaterialDensity: p.lineMaterial?.density,
    };
    rows.push(CSV_COLS.map((c) => csvCell(flat[c])).join(','));
  }
  return rows.join('\n') + '\n';
}

/**
 * Full-text CSV parser: records split on unquoted newlines (a quoted cell
 * may contain commas, quotes AND newlines — presetsToCsv writes all three).
 */
function parseCsv(csv: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let cur = '';
  let quoted = false;
  for (let i = 0; i < csv.length; i++) {
    const ch = csv[i]!;
    if (quoted) {
      if (ch === '"' && csv[i + 1] === '"') { cur += '"'; i++; }
      else if (ch === '"') quoted = false;
      else cur += ch;
    } else if (ch === '"') quoted = true;
    else if (ch === ',') { row.push(cur); cur = ''; }
    else if (ch === '\n' || ch === '\r') {
      if (ch === '\r' && csv[i + 1] === '\n') i++;
      row.push(cur); cur = '';
      rows.push(row); row = [];
    } else cur += ch;
  }
  if (cur !== '' || row.length > 0) { row.push(cur); rows.push(row); }
  return rows.filter((r) => r.some((c) => c.trim() !== ''));
}

/** Parses an edited CSV back into presets (SI values, same columns as export). */
export function csvToPresets(csv: string): Preset[] {
  const records = parseCsv(csv);
  if (records.length < 2) return [];
  const header = records[0]!.map((h) => h.trim());
  const out: Preset[] = [];
  for (const cells of records.slice(1)) {
    const row: Record<string, string> = {};
    // csvCell prefixes ONE apostrophe to a cell a spreadsheet would read as a
    // formula (see csvUtil.ts). Strip exactly one back off, or a preset this app
    // exported and re-imported comes back with a literal ' on its part number.
    // Numeric columns are unaffected: Number("'-1") is NaN either way.
    header.forEach((h, i) => { row[h] = (cells[i] ?? '').replace(/^'/, ''); });
    if (!row['kind'] || !row['partNo']) continue;
    const p: Preset = {
      kind: CANONICAL_KIND.get(row['kind']!.trim().toLowerCase()) ?? row['kind']!.trim(),
      manufacturer: row['manufacturer'] || 'Custom',
      partNo: row['partNo']!,
      description: row['description'] ?? '',
    };
    // A non-numeric density is left AS PARSED, deliberately. PresetPicker's
    // rowIsSound refuses the row and names its part number, so the user can go
    // and fix it; dropping the material here instead would import the row clean
    // and silently weightless, which is the failure this was meant to stop.
    // A HALF-FILLED PAIR goes the same way (2026-09-21): `&&` here meant a
    // name with no density skipped the material block entirely and imported as
    // a clean success, so the part kept its old weight under a new label —
    // exactly the silent case the paragraph above refuses.
    if (row['materialName'] || row['materialDensity']) {
      p.material = {
        name: row['materialName']!,
        type: row['materialType'] || (SURFACE_KINDS.has(p.kind) ? 'SURFACE' : 'BULK'),
        density: Number(row['materialDensity']),
      };
    }
    if (row['lineMaterialName'] || row['lineMaterialDensity']) {
      p.lineMaterial = {
        name: row['lineMaterialName']!,
        type: 'LINE',
        density: Number(row['lineMaterialDensity']),
      };
    }
    for (const c of CSV_COLS) {
      if (['kind', 'manufacturer', 'partNo', 'description', 'materialName', 'materialType', 'materialDensity', 'shape', 'filled', 'lineMaterialName', 'lineMaterialDensity'].includes(c)) continue;
      // TRIM BEFORE TESTING. `Number(' ')` is 0 and `' ' !== ''`, so a cell a
      // spreadsheet left holding a single space imported as the NUMBER ZERO —
      // a zero mass (which used to become `overrideMass: 0`), a zero diameter,
      // a zero length — rather than being skipped as the blank it is.
      const raw = (row[c] ?? '').trim();
      const v = Number(raw);
      if (raw !== '' && Number.isFinite(v)) p[c] = v;
    }
    if (row['shape']) p['shape'] = row['shape'];
    if (row['filled'] === 'true') p['filled'] = true;
    out.push(p);
  }
  return out;
}

// ---------------------------------------------------------------------------
// Catalogue links on import (ruled 2026-09-03)
// ---------------------------------------------------------------------------

/**
 * A part an importer read together with the catalogue identity the file gave
 * it — RockSim's <PartMfg>/<PartNo>, desktop's <preset manufacturer partno>.
 * Resolved once the whole tree is built (applyPresetLinks), so "the file left
 * it unset" is judged against everything the file said about the part.
 */
export interface PendingPresetLink {
  node: ComponentNode;
  manufacturer: string;
  partNo: string;
}

/** The lookup key the preset pipeline dedupes on: kind | manufacturer | part number. */
const linkKey = (kind: string, manufacturer: unknown, partNo: unknown): string =>
  `${kind}|${mfrKey(manufacturer)}|${partKey(partNo)}`;

/**
 * Is this node's mass override the catalogue mass of the part it is linked to
 * — one `presetPatch` wrote, or a file copied from the same row — rather than a
 * weight the user typed? `presetPatch` clears the first kind on a pick and
 * never the second (review of audit 2026-09-22: clearing every override threw
 * away a user's weighed mass on 1,197 of the 1,308 body-tube rows, which carry
 * none). Matched on the key applyPresetLinks matches on, alternate part numbers
 * included, and to 0.01 % so a mass that has been through a saved file still
 * reads as the catalogue's (a user who typed the catalogue's own figure has, in
 * effect, kept the catalogue's mass, and it goes with that part).
 */
export function holdsCatalogueMass(node: ComponentNode, presets: readonly Preset[]): boolean {
  const held = node['overrideMass'];
  const kind = KIND_FOR_TYPE[node.type];
  if (typeof held !== 'number' || !kind || node['presetPartNo'] == null) return false;
  const want = linkKey(kind, node['presetManufacturer'], node['presetPartNo']);
  return presets.some((p) => {
    if (p.kind !== kind || !(typeof p.mass === 'number' && p.mass > 0)) return false;
    if (Math.abs(held - p.mass) > 1e-4 * p.mass) return false;
    const alts = Array.isArray(p['altPartNos']) ? (p['altPartNos'] as unknown[]) : [];
    return [p.partNo, ...alts].some((pn) => linkKey(kind, p.manufacturer, pn) === want);
  });
}

/** Plain words for the import note — a user reads "drag coefficient", not "cd". */
const FIELD_WORDS: Record<string, string> = {
  cd: 'drag coefficient', spillHoleDiameter: 'spill hole',
  diameter: 'diameter', lineCount: 'line count', lineLength: 'line length',
  surfaceDensity: 'canopy material', surfaceMaterialName: 'canopy material',
  lineDensity: 'line material', lineMaterialName: 'line material',
  density: 'material', materialName: 'material', length: 'length', outerRadius: 'outer radius',
  aftRadius: 'base radius', foreRadius: 'fore radius', thickness: 'wall thickness', shape: 'shape',
  shapeParameter: 'shape parameter', filled: 'solid', shoulderRadius: 'shoulder radius',
  shoulderLength: 'shoulder length', stripLength: 'strip length', stripWidth: 'strip width',
};

/**
 * Link imported parts to the catalogue. The owner's ruling (2026-09-03): "if a
 * file is imported and the parachute in the file does match a chute in our
 * parts database, we should import the settings from our database."
 *
 * PRECEDENCE. The file's explicit values stand; the catalogue fills only what
 * the file left unset. That is desktop OpenRocket's own order — its saver writes
 * <preset> first and every explicit element after it, so the explicit values win
 * on load — and it is the rule that does not snap a body tube the author cut to
 * length back to the catalogue's stock length. For a RockSim chute the unset
 * field is exactly the one that matters: its <DragCoefficient>0.75 is the
 * "auto" sentinel, which the importer does not pin, so the catalogue's real Cd
 * lands here (2.2 on a Fruity Chutes toroidal against the kernel default 0.8 —
 * the difference between failing and passing the 20 ft/s landing check on a
 * correctly built rocket).
 *
 * THE MASS IS NEVER TAKEN FROM THE CATALOGUE. RockSim keeps <PartNo> on a part
 * the author has since cut down, so a stock mass would land on a shortened
 * tube; the file's own mass model (density × geometry, or its measured mass) is
 * the author's and stays. Desktop clears its preset link the moment a dimension
 * is edited, which is why the same hazard does not arise for .ork.
 *
 * Returns how many parts were linked; appends one plain-language note.
 */
export function applyPresetLinks(
  pending: readonly PendingPresetLink[],
  presets: readonly Preset[] | undefined,
  notes: string[],
): number {
  if (!presets?.length || pending.length === 0) return 0;
  const byKey = new Map<string, Preset>();
  for (const p of presets) {
    const k = linkKey(p.kind, p.manufacturer, p.partNo);
    if (!byKey.has(k)) byKey.set(k, p);
    // A row can answer to part numbers it has absorbed. The ten RockSim Fruity
    // Chutes rows were dropped as duplicates on 2026-09-03, but `.rkt` FILES
    // still name them — Eric's own Wildman carries <PartNo>29185</PartNo> — so
    // the numbers ride on the surviving row. Dropping a duplicate must never
    // cost a file its catalogue link.
    const alts = p['altPartNos'];
    if (Array.isArray(alts)) {
      for (const alt of alts) {
        const ak = linkKey(p.kind, p.manufacturer, alt);
        if (!byKey.has(ak)) byKey.set(ak, p);
      }
    }
  }
  const lines: string[] = [];
  /** Tier (a) of the conflict marker: one line per part whose stated values disagree with its row. */
  const conflictLines: string[] = [];
  let linked = 0;
  for (const { node, manufacturer, partNo } of pending) {
    const kind = KIND_FOR_TYPE[node.type];
    if (!kind) continue;
    const p = byKey.get(linkKey(kind, manufacturer, partNo));
    if (!p) continue;
    const patch = presetPatch(node.type, p) as Record<string, unknown>;
    const filled = new Set<string>();
    // THE CANOPY PAIR IS EXEMPT FROM THE PER-KEY GATE BELOW.
    //
    // A rated Cd and its spill hole are ONE fact (standing ruling, 2026-09-03):
    // the maker measures Cd against the canopy area MINUS the vent, and the
    // kernel re-derives that same area as 1 − (d/D)² of the nominal disc. Filling
    // them independently grafts the catalogue's half onto the file's half. The
    // real case: a .rkt naming Fruity Chutes CFC-015-N whose author typed their
    // own 1.5 in vent on the 15 in canopy. RockSim's <DragCoefficient>0.75 is the
    // "auto" sentinel the importer does not pin, so `cd` was unset and the
    // catalogue's 1.5 landed — a figure measured against the maker's 20 % vent —
    // while the file's own 10 % vent stayed, applying 0.99 where 0.96 was meant:
    // CdA 3.1 % high, descent rate 1.5 % LOW, which is the optimistic direction.
    //
    // So the pair moves together or not at all, and that holds in REVERSE too:
    // the catalogue's vent never lands on a Cd the file stated. A row with no
    // `spillHoleDiameter` is a whole fact (an unvented canopy) and may still
    // supply its Cd; a row with a vent but no Cd is half of one, and supplies
    // neither.
    // Only a CANOPY has the pair: a streamer's Cd is referenced to strip area
    // and it has no vent, so it keeps the plain per-key gate below.
    const isCanopy = node.type === 'parachute';
    const PAIR = ['cd', 'spillHoleDiameter'] as const;
    const canopyStatesHalf = isCanopy && PAIR.some((k) => node[k] !== undefined);
    const takePair = patch['cd'] !== undefined && !canopyStatesHalf;
    /**
     * A WALL THICKNESS IS A STATEMENT THAT THE PART IS HOLLOW (audit 2026-09-22).
     * The .ork reader marks a solid part `filled: true` and a hollow one only by
     * its numeric <thickness> — desktop's own setThickness clears `filled` — so
     * "filled is unset" on such a node is not "the file left it unset". Before
     * this, the catalogue's `filled: true` landed on hollow noses a file had
     * modelled with a wall: 19.6 g → 107.8 g (Rocketarium HIPS) and 103.1 g →
     * 907.4 g (Madcow 2.6" fiberglass), overstating stability, from any file.
     * Read as `filled: false` for both the fill and the conflict marker. (The
     * RockSim reader now writes the `false` itself; this covers every reader.)
     */
    const statesHollow = (node.type === 'nosecone' || node.type === 'transition')
      && node['filled'] === undefined && typeof node['thickness'] === 'number';
    const stated = (key: string): unknown => (key === 'filled' && statesHollow ? false : node[key]);
    /**
     * THE CONFLICT MARKER, tier (a) — the owner's caveat on the precedence
     * ruling (issues-2026-09-03b.md:26: *"in the case where file's explicit
     * values are in conflict with catalogue values, should we warn the user?
     * … we don't want to nag them"*), approved 2026-09-07. The file's value
     * STANDS — that is the ruling and it does not change here — but where it
     * disagrees with the catalogue row it was matched to, the note says so,
     * once, in one sentence. Nothing is stored and nothing is dismissed: the
     * only ways to make it go away are real edits that already persist.
     *
     * Read BEFORE any assignment in the loop below, so it only ever compares
     * a value the file stated with the catalogue's — never a value this loop
     * just filled in. The canopy pair is compared only when the file states
     * BOTH halves: half a pair against a whole one is not a disagreement about
     * the same fact.
     */
    const conflicts: string[] = [];
    for (const [key, value] of Object.entries(patch)) {
      if (value === undefined || key === 'name' || key === 'overrideMass') continue;
      if (key === 'presetManufacturer' || key === 'presetPartNo') continue;
      const have = stated(key);
      if (have === undefined) continue;
      if (isCanopy && (key === 'cd' || key === 'spillHoleDiameter')
        && !PAIR.every((k) => node[k] !== undefined)) continue;
      if (typeof value === 'number' && typeof have === 'number') {
        // A tolerance, not equality: a .rkt stores 25.4 mm as 25.4000 and a
        // catalogue row as 0.0254 m, which round-trips to the same number only
        // to ~1e-12. 0.5 % is well inside any real disagreement and outside
        // any unit conversion.
        const scale = Math.max(Math.abs(value), Math.abs(have), 1e-9);
        if (Math.abs(value - have) / scale > 0.005) conflicts.push(FIELD_WORDS[key] ?? key);
      } else if (typeof value === 'string' && typeof have === 'string') {
        if (value.trim().toLowerCase() !== have.trim().toLowerCase()) conflicts.push(FIELD_WORDS[key] ?? key);
      } else if (typeof value === 'boolean' && typeof have === 'boolean') {
        if (value !== have) conflicts.push(FIELD_WORDS[key] ?? key);
      }
    }
    for (const [key, value] of Object.entries(patch)) {
      if (value === undefined || key === 'name' || key === 'overrideMass') continue;
      if (key === 'presetManufacturer' || key === 'presetPartNo') {
        node[key] = value;
        continue;
      }
      if (isCanopy && (key === 'cd' || key === 'spillHoleDiameter')) {
        if (!takePair) continue;
        node[key] = value;
        filled.add(FIELD_WORDS[key] ?? key);
        continue;
      }
      // A hollow row's `filled: false` is the default an unset node already
      // flies, so there is nothing to fill — and "took solid from the
      // catalogue" would be a false note.
      if (key === 'filled' && value === false) continue;
      if (stated(key) === undefined) {
        node[key] = value;
        filled.add(FIELD_WORDS[key] ?? key);
      }
    }
    linked += 1;
    if (conflicts.length) conflictLines.push(`${node.name ?? node.type}: ${[...new Set(conflicts)].join(', ')}`);
    const took = filled.size ? ` — took ${[...filled].join(', ')} from the catalogue` : '';
    // Said out loud, because a silently missing Cd is how the 0.8 default gets
    // blamed on the catalogue instead of on the pairing rule.
    const declined = canopyStatesHalf && patch['cd'] !== undefined
      ? ' — left the catalogue’s drag coefficient and spill hole out: this file already'
        + ' states one of the pair, and the two are one number together'
      : '';
    lines.push(`${node.name ?? node.type} → ${p.manufacturer} ${p.partNo}${took}${declined}`);
  }
  if (linked > 0) {
    notes.push(
      `${linked} part${linked === 1 ? '' : 's'} matched the parts catalogue by manufacturer and part number. `
      + `The file's own values stand; the catalogue filled in only what the file left unset: ${lines.join('; ')}.`,
    );
    // Said once, after the match sentence, and only when there is something to
    // say. It names the parts and the fields so a reader can go and look, and
    // it says what was kept — the file — so nobody reads it as a change.
    if (conflictLines.length) {
      const n = conflictLines.length;
      notes.push(
        `${n} of ${n === 1 ? 'those parts states' : 'those parts state'} a value that disagrees with `
        + `${n === 1 ? 'its' : 'their'} catalogue row — the file's value was kept: ${conflictLines.join('; ')}.`,
      );
    }
  }
  return linked;
}
