import type { ComponentNode, ComponentType } from '@online-openrocket/engine';
import { csvCell } from './csvUtil.js';
// The ONE manufacturer alias table + part-number key, shared with the preset
// pipeline so the app matches a file's part the same way the database dedupes.
import { mfrKey, partKey } from '../../scripts/manufacturers.mjs';

/**
 * Component preset database (openrocket-database .orc files → presets.json,
 * regenerated by scripts/fetch-component-presets.mjs; all SI). The bundle is
 * ~1.3 MB so it loads lazily on first use. User presets imported from CSV
 * are stored in localStorage and merged in.
 */

export interface Preset {
  kind: string;
  manufacturer: string;
  partNo: string;
  description: string;
  material?: { name: string; type: string; density: number };
  lineMaterial?: { name: string; type: string; density: number };
  mass?: number;
  [dim: string]: unknown;
}

/** .orc kind → editor component type. */
export const KIND_FOR_TYPE: Partial<Record<ComponentType, string>> = {
  bodytube: 'BodyTube',
  // Inner tubes consume the BODY TUBE catalogue — desktop's own rule
  // (InnerTube.getPresetType() returns Type.BODY_TUBE; there is no InnerTube
  // preset kind in the .orc format at all). Until v0.089 this entry was
  // missing, so a motor-mount tube offered no preset picker whatsoever — and
  // the Composite Warehouse motor-mount tubes are exactly the rows a mount
  // wants.
  innertube: 'BodyTube',
  nosecone: 'NoseCone',
  transition: 'Transition',
  centeringring: 'CenteringRing',
  tubecoupler: 'TubeCoupler',
  bulkhead: 'BulkHead',
  engineblock: 'EngineBlock',
  launchlug: 'LaunchLug',
  parachute: 'Parachute',
  streamer: 'Streamer',
};

let bundled: Preset[] | null = null;

export async function loadPresets(): Promise<Preset[]> {
  if (!bundled) {
    const mod = await import('../data/presets.json');
    bundled = (mod.default as { presets: Preset[] }).presets;
  }
  return [...bundled, ...loadCustomPresets()];
}

const CUSTOM_KEY = 'online-openrocket.custom-presets.v1';

export function loadCustomPresets(): Preset[] {
  try {
    const raw = localStorage.getItem(CUSTOM_KEY);
    return raw ? (JSON.parse(raw) as Preset[]) : [];
  } catch {
    return [];
  }
}

export function saveCustomPresets(presets: Preset[]): void {
  try {
    localStorage.setItem(CUSTOM_KEY, JSON.stringify(presets));
  } catch {
    // Private browsing / quota — the presets still work for this session.
  }
}

const n = (p: Preset, key: string): number | undefined =>
  typeof p[key] === 'number' ? (p[key] as number) : undefined;

/**
 * Preset → node patch (editor params, SI). Same semantics as the desktop:
 * dimensions and material apply; a cataloged mass becomes a mass override
 * (real parts weigh what they weigh, not what the geometry computes).
 */
export function presetPatch(type: ComponentType, p: Preset): Partial<ComponentNode> {
  const patch: Partial<ComponentNode> = { name: `${p.manufacturer} ${p.partNo}` };
  const half = (v: number | undefined) => (v === undefined ? undefined : v / 2);
  const set = (key: string, v: unknown) => {
    if (v !== undefined && v !== null) (patch as Record<string, unknown>)[key] = v;
  };

  if (p.material?.type === 'BULK') {
    set('materialName', p.material.name);
    set('density', p.material.density);
  }
  if (p.mass !== undefined) set('overrideMass', p.mass);
  // The catalogue identity rides with the part, so a saved .rkt names the row
  // it came from (<PartMfg>/<PartNo>) and an import can find it again.
  set('presetManufacturer', p.manufacturer);
  set('presetPartNo', p.partNo);

  const out = n(p, 'outsideDiameter');
  const inn = n(p, 'insideDiameter');
  switch (type) {
    case 'bodytube':
    case 'tubecoupler':
    case 'innertube':
      set('length', n(p, 'length'));
      set('outerRadius', half(out));
      if (out !== undefined && inn !== undefined) set('thickness', (out - inn) / 2);
      break;
    case 'nosecone':
      set('length', n(p, 'length'));
      set('aftRadius', half(out));
      set('shape', typeof p['shape'] === 'string' ? (p['shape'] as string).toLowerCase() : undefined);
      if (p['filled'] === true) set('filled', true);
      set('shoulderRadius', half(n(p, 'shoulderDiameter')));
      set('shoulderLength', n(p, 'shoulderLength'));
      set('thickness', n(p, 'thickness'));
      break;
    case 'transition':
      set('length', n(p, 'length'));
      set('foreRadius', half(n(p, 'foreOutsideDiameter')));
      set('aftRadius', half(n(p, 'aftOutsideDiameter')));
      set('shape', typeof p['shape'] === 'string' ? (p['shape'] as string).toLowerCase() : undefined);
      // A balsa reducer is solid. Until v0.097 only the nose-cone branch honoured
      // `filled`, so every one of the 314 catalogue transitions marked solid and
      // carrying no catalogue mass applied as a hollow 2 mm shell - measured
      // 1.129 g against 5.026 g on one SEMROC part, a 4.5x mass error. Ruled
      // 2026-09-03: "Fix it."
      if (p['filled'] === true) set('filled', true);
      set('foreShoulderRadius', half(n(p, 'foreShoulderDiameter')));
      set('foreShoulderLength', n(p, 'foreShoulderLength'));
      set('aftShoulderRadius', half(n(p, 'aftShoulderDiameter')));
      set('aftShoulderLength', n(p, 'aftShoulderLength'));
      set('thickness', n(p, 'thickness'));
      break;
    case 'centeringring':
    case 'bulkhead':
      set('length', n(p, 'length'));
      break;
    case 'engineblock':
      set('length', n(p, 'length'));
      if (out !== undefined && inn !== undefined) set('thickness', (out - inn) / 2);
      break;
    case 'launchlug':
      set('length', n(p, 'length'));
      set('outerRadius', half(out));
      if (out !== undefined && inn !== undefined) set('thickness', (out - inn) / 2);
      break;
    case 'parachute': {
      set('diameter', n(p, 'diameter'));
      // Manufacturer-rated canopy Cd (referenced to the nominal diameter).
      // Dropping this silently falls back to the kernel default 0.8 — a
      // Fruity Chutes Iris Ultra (Cd 2.2) then descends 1.66× too fast.
      const cd = n(p, 'dragCoefficient');
      if (cd !== undefined && cd > 0) set('cd', cd);
      set('lineCount', n(p, 'lineCount'));
      set('lineLength', n(p, 'lineLength'));
      if (p.material?.type === 'SURFACE') {
        set('surfaceMaterialName', p.material.name);
        set('surfaceDensity', p.material.density);
      }
      if (p.lineMaterial) {
        set('lineMaterialName', p.lineMaterial.name);
        set('lineDensity', p.lineMaterial.density);
      }
      break;
    }
    case 'streamer': {
      set('stripLength', n(p, 'length'));
      set('stripWidth', n(p, 'width'));
      const scd = n(p, 'dragCoefficient');
      if (scd !== undefined && scd > 0) set('cd', scd);
      if (p.material?.type === 'SURFACE') {
        set('surfaceMaterialName', p.material.name);
        set('surfaceDensity', p.material.density);
      }
      break;
    }
  }
  return patch;
}

// ---------------- CSV round-trip ----------------

const CSV_COLS = [
  'kind', 'manufacturer', 'partNo', 'description', 'materialName', 'materialType',
  'materialDensity', 'mass', 'length', 'outsideDiameter', 'insideDiameter', 'shape',
  'filled', 'shoulderDiameter', 'shoulderLength', 'thickness', 'foreOutsideDiameter',
  'aftOutsideDiameter', 'foreShoulderDiameter', 'foreShoulderLength',
  'aftShoulderDiameter', 'aftShoulderLength', 'diameter', 'dragCoefficient',
  'lineCount', 'lineLength', 'width',
  'lineMaterialName', 'lineMaterialDensity',
];

export function presetsToCsv(presets: Preset[]): string {
  const rows = [CSV_COLS.join(',')];
  for (const p of presets) {
    const flat: Record<string, unknown> = {
      ...p,
      materialName: p.material?.name,
      materialType: p.material?.type,
      materialDensity: p.material?.density,
      lineMaterialName: p.lineMaterial?.name,
      lineMaterialDensity: p.lineMaterial?.density,
    };
    rows.push(CSV_COLS.map((c) => csvCell(flat[c])).join(','));
  }
  return rows.join('\n') + '\n';
}

/**
 * Full-text CSV parser: records split on unquoted newlines (a quoted cell
 * may contain commas, quotes AND newlines — presetsToCsv writes all three).
 */
function parseCsv(csv: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let cur = '';
  let quoted = false;
  for (let i = 0; i < csv.length; i++) {
    const ch = csv[i]!;
    if (quoted) {
      if (ch === '"' && csv[i + 1] === '"') { cur += '"'; i++; }
      else if (ch === '"') quoted = false;
      else cur += ch;
    } else if (ch === '"') quoted = true;
    else if (ch === ',') { row.push(cur); cur = ''; }
    else if (ch === '\n' || ch === '\r') {
      if (ch === '\r' && csv[i + 1] === '\n') i++;
      row.push(cur); cur = '';
      rows.push(row); row = [];
    } else cur += ch;
  }
  if (cur !== '' || row.length > 0) { row.push(cur); rows.push(row); }
  return rows.filter((r) => r.some((c) => c.trim() !== ''));
}

/** Parses an edited CSV back into presets (SI values, same columns as export). */
export function csvToPresets(csv: string): Preset[] {
  const records = parseCsv(csv);
  if (records.length < 2) return [];
  const header = records[0]!.map((h) => h.trim());
  const out: Preset[] = [];
  for (const cells of records.slice(1)) {
    const row: Record<string, string> = {};
    header.forEach((h, i) => { row[h] = cells[i] ?? ''; });
    if (!row['kind'] || !row['partNo']) continue;
    const p: Preset = {
      kind: row['kind']!,
      manufacturer: row['manufacturer'] || 'Custom',
      partNo: row['partNo']!,
      description: row['description'] ?? '',
    };
    if (row['materialName'] && row['materialDensity']) {
      p.material = {
        name: row['materialName']!,
        type: row['materialType'] || 'BULK',
        density: Number(row['materialDensity']),
      };
    }
    if (row['lineMaterialName'] && row['lineMaterialDensity']) {
      p.lineMaterial = {
        name: row['lineMaterialName']!,
        type: 'LINE',
        density: Number(row['lineMaterialDensity']),
      };
    }
    for (const c of CSV_COLS) {
      if (['kind', 'manufacturer', 'partNo', 'description', 'materialName', 'materialType', 'materialDensity', 'shape', 'filled', 'lineMaterialName', 'lineMaterialDensity'].includes(c)) continue;
      const v = Number(row[c]);
      if (row[c] !== '' && Number.isFinite(v)) p[c] = v;
    }
    if (row['shape']) p['shape'] = row['shape'];
    if (row['filled'] === 'true') p['filled'] = true;
    out.push(p);
  }
  return out;
}

// ---------------------------------------------------------------------------
// Catalogue links on import (ruled 2026-09-03)
// ---------------------------------------------------------------------------

/**
 * A part an importer read together with the catalogue identity the file gave
 * it — RockSim's <PartMfg>/<PartNo>, desktop's <preset manufacturer partno>.
 * Resolved once the whole tree is built (applyPresetLinks), so "the file left
 * it unset" is judged against everything the file said about the part.
 */
export interface PendingPresetLink {
  node: ComponentNode;
  manufacturer: string;
  partNo: string;
}

/** The lookup key the preset pipeline dedupes on: kind | manufacturer | part number. */
const linkKey = (kind: string, manufacturer: unknown, partNo: unknown): string =>
  `${kind}|${mfrKey(manufacturer)}|${partKey(partNo)}`;

/** Plain words for the import note — a user reads "drag coefficient", not "cd". */
const FIELD_WORDS: Record<string, string> = {
  cd: 'drag coefficient', diameter: 'diameter', lineCount: 'line count', lineLength: 'line length',
  surfaceDensity: 'canopy material', surfaceMaterialName: 'canopy material',
  lineDensity: 'line material', lineMaterialName: 'line material',
  density: 'material', materialName: 'material', length: 'length', outerRadius: 'outer radius',
  aftRadius: 'base radius', foreRadius: 'fore radius', thickness: 'wall thickness', shape: 'shape',
  shapeParameter: 'shape parameter', filled: 'solid', shoulderRadius: 'shoulder radius',
  shoulderLength: 'shoulder length', stripLength: 'strip length', stripWidth: 'strip width',
};

/**
 * Link imported parts to the catalogue. The owner's ruling (2026-09-03): "if a
 * file is imported and the parachute in the file does match a chute in our
 * parts database, we should import the settings from our database."
 *
 * PRECEDENCE. The file's explicit values stand; the catalogue fills only what
 * the file left unset. That is desktop OpenRocket's own order — its saver writes
 * <preset> first and every explicit element after it, so the explicit values win
 * on load — and it is the rule that does not snap a body tube the author cut to
 * length back to the catalogue's stock length. For a RockSim chute the unset
 * field is exactly the one that matters: its <DragCoefficient>0.75 is the
 * "auto" sentinel, which the importer does not pin, so the catalogue's real Cd
 * lands here (2.2 on a Fruity Chutes toroidal against the kernel default 0.8 —
 * the difference between failing and passing the 20 ft/s landing check on a
 * correctly built rocket).
 *
 * THE MASS IS NEVER TAKEN FROM THE CATALOGUE. RockSim keeps <PartNo> on a part
 * the author has since cut down, so a stock mass would land on a shortened
 * tube; the file's own mass model (density × geometry, or its measured mass) is
 * the author's and stays. Desktop clears its preset link the moment a dimension
 * is edited, which is why the same hazard does not arise for .ork.
 *
 * Returns how many parts were linked; appends one plain-language note.
 */
export function applyPresetLinks(
  pending: readonly PendingPresetLink[],
  presets: readonly Preset[] | undefined,
  notes: string[],
): number {
  if (!presets?.length || pending.length === 0) return 0;
  const byKey = new Map<string, Preset>();
  for (const p of presets) {
    const k = linkKey(p.kind, p.manufacturer, p.partNo);
    if (!byKey.has(k)) byKey.set(k, p);
  }
  const lines: string[] = [];
  let linked = 0;
  for (const { node, manufacturer, partNo } of pending) {
    const kind = KIND_FOR_TYPE[node.type];
    if (!kind) continue;
    const p = byKey.get(linkKey(kind, manufacturer, partNo));
    if (!p) continue;
    const patch = presetPatch(node.type, p) as Record<string, unknown>;
    const filled = new Set<string>();
    for (const [key, value] of Object.entries(patch)) {
      if (value === undefined || key === 'name' || key === 'overrideMass') continue;
      if (key === 'presetManufacturer' || key === 'presetPartNo') {
        node[key] = value;
        continue;
      }
      if (node[key] === undefined) {
        node[key] = value;
        filled.add(FIELD_WORDS[key] ?? key);
      }
    }
    linked += 1;
    const took = filled.size ? ` — took ${[...filled].join(', ')} from the catalogue` : '';
    lines.push(`${node.name ?? node.type} → ${p.manufacturer} ${p.partNo}${took}`);
  }
  if (linked > 0) {
    notes.push(
      `${linked} part${linked === 1 ? '' : 's'} matched the parts catalogue by manufacturer and part number. `
      + `The file's own values stand; the catalogue filled in only what the file left unset: ${lines.join('; ')}.`,
    );
  }
  return linked;
}
