import type { ComponentNode, ComponentType } from '@online-openrocket/engine';
import { csvCell } from './csvUtil.js';
import { lookupTable, parseDecimal } from './xmlUtil.js';
import { numOpt } from '../tree/nodeNum.js';
import { blankValue } from '../tree/schema.js';
// The ONE manufacturer alias table + part-number key, shared with the preset
// pipeline so the app matches a file's part the same way the database dedupes.
import { mfrKey, partKey } from '../../scripts/manufacturers.mjs';

/**
 * Component preset database (openrocket-database .orc files → presets.json,
 * regenerated by scripts/fetch-component-presets.mjs; all SI). The bundle is
 * ~1.3 MB so it loads lazily on first use. User presets imported from CSV
 * are stored in localStorage and merged in.
 */

export interface Preset {
  kind: string;
  manufacturer: string;
  partNo: string;
  description: string;
  material?: { name: string; type: string; density: number };
  lineMaterial?: { name: string; type: string; density: number };
  mass?: number;
  [dim: string]: unknown;
}

/** .orc kind → editor component type. */
export const KIND_FOR_TYPE = lookupTable<string>({
  bodytube: 'BodyTube',
  // Inner tubes consume the BODY TUBE catalogue — desktop's own rule
  // (InnerTube.getPresetType() returns Type.BODY_TUBE; there is no InnerTube
  // preset kind in the .orc format at all). Until v0.089 this entry was
  // missing, so a motor-mount tube offered no preset picker whatsoever — and
  // the Composite Warehouse motor-mount tubes are exactly the rows a mount
  // wants.
  innertube: 'BodyTube',
  nosecone: 'NoseCone',
  transition: 'Transition',
  centeringring: 'CenteringRing',
  tubecoupler: 'TubeCoupler',
  bulkhead: 'BulkHead',
  engineblock: 'EngineBlock',
  launchlug: 'LaunchLug',
  parachute: 'Parachute',
  streamer: 'Streamer',
} satisfies Partial<Record<ComponentType, string>>) as Partial<Record<ComponentType, string>>;

/**
 * DESKTOP'S OWN LINK for a part, as an .ork's `<preset>` stated it — kept
 * verbatim so a save hands desktop back the row it chose (orkFile.ts, the
 * writer's `presetLink`, has why: desktop finds a row by a digest of its own
 * that this app cannot compute). Part of the link (CATALOGUE_LINK_KEYS): a
 * pick replaces it, Detach clears it.
 */
export const ORK_PRESET_KEYS = {
  manufacturer: 'orkPresetManufacturer',
  partNo: 'orkPresetPartNo',
  digest: 'orkPresetDigest',
} as const;

let bundled: Preset[] | null = null;

export async function loadPresets(): Promise<Preset[]> {
  if (!bundled) {
    const mod = await import('../data/presets.json');
    bundled = (mod.default as { presets: Preset[] }).presets;
  }
  return [...bundled, ...loadCustomPresets()];
}

const CUSTOM_KEY = 'online-openrocket.custom-presets.v1';

export function loadCustomPresets(): Preset[] {
  try {
    const raw = localStorage.getItem(CUSTOM_KEY);
    return raw ? (JSON.parse(raw) as Preset[]) : [];
  } catch {
    return [];
  }
}

export function saveCustomPresets(presets: Preset[]): void {
  try {
    localStorage.setItem(CUSTOM_KEY, JSON.stringify(presets));
  } catch {
    // Private browsing / quota — the presets still work for this session.
  }
}

const n = (p: Preset, key: string): number | undefined => numOpt(p, key);

/**
 * Preset → node patch (editor params, SI). Desktop's semantics for dimensions
 * and material; a cataloged mass becomes a mass override on every part, where
 * desktop does that for a parachute only (real parts weigh what they weigh, not
 * what the geometry computes).
 *
 * THE PATCH DESCRIBES THE WHOLE PART, not only the fields the row happens to
 * carry (audit 2026-09-22). It is merged over the node (`updateNode` spreads
 * it), so a field the row lacks used to keep whatever the PREVIOUS part left
 * there — and trying one catalogue part and then another is ordinary. Measured
 * then: Fruity Chutes IFC-030-S followed by Apogee 29093 (no Cd, no vent) flew
 * the Fruity Chutes Cd 2.2 and its vent on the Apogee canopy, a flown Cd of
 * 2.09 where desktop flies the 0.8 default, so the rocket came down at 1.14 m/s
 * instead of 1.84 — the optimistic direction; and an Apogee 19490 thin-wall
 * nose applied after a solid cone stayed solid, 975.8 g instead of 86.5 g. So
 * every field this function OWNS is written either way: the row's value, or
 * `undefined`, which is how this app says "the default" (`updateNode` spreads
 * it over the old value, JSON drops it on the way to the kernel, and the kernel
 * applies its own default — the same one desktop's loadFromPreset resets to).
 * The mass override is the one exception, and has its own rule below: a user's
 * weighed mass is theirs, not the part's.
 *
 * `applyPresetLinks` below skips every undefined entry, so a catalogue link on
 * import still only ever FILLS what a file left unset; a clear here never
 * erases a value a file stated.
 */
export function presetPatch(
  type: ComponentType,
  p: Preset,
  /**
   * The part being replaced, and the catalogue it may have been picked from.
   * Only the mass override reads them, to tell a catalogue mass (the patch's to
   * clear) from a weight the user typed (never its to clear). The picker passes
   * both; without them nothing that might be the user's is cleared.
   */
  prior?: { node: ComponentNode; presets: readonly Preset[] },
): Partial<ComponentNode> {
  const patch: Partial<ComponentNode> = { name: `${p.manufacturer} ${p.partNo}` };
  const half = (v: number | undefined) => (v === undefined ? undefined : v / 2);
  const set = (key: string, v: unknown) => {
    if (v !== undefined && v !== null) (patch as Record<string, unknown>)[key] = v;
  };
  /** An owned field: the row's value, or back to the default when the row has none. */
  const own = (key: string, v: unknown) => {
    (patch as Record<string, unknown>)[key] = v === null ? undefined : v;
  };

  if (p.material?.type === 'BULK') {
    set('materialName', p.material.name);
    set('density', p.material.density);
  }
  // A catalogued mass of ZERO is not a part that weighs nothing, it is a row
  // that states no mass — and `overrideMass: 0` makes the component contribute
  // nothing at all while every other field still looks right, which on a nose
  // cone or a coupler moves the CG and the stability margin silently. No
  // shipped row carries mass 0 (measured over presets.json, 2026-09-04); the
  // guard is for the CSV import loop below, where a user can type one.
  //
  // WHAT A PICK DOES TO A MASS OVERRIDE (audit 2026-09-22, narrowed on review).
  // Desktop's loadFromPreset touches the mass on a PARACHUTE — the row's mass,
  // or back to computed (Parachute: massOverridden = false) — and on no other
  // part this picker serves, so a weight the user typed survives a change of
  // part. This app writes a catalogued mass as the override on EVERY part, so
  // it owes a clear of what it wrote, and nothing more:
  //  - a row with a mass writes it, and drops the subcomponents flag with it: a
  //    catalogue mass is one part's weight, never an assembly's. Left on, the
  //    flag made that weight the whole subtree's — a tube's fins, mount and
  //    everything under it together weighing the tube's 5.8 g;
  //  - a row with no mass clears the override (and flag, the pair the panel's
  //    Mass field clears together) where it is the PREVIOUS part's catalogue
  //    mass — else that part's weight rode onto this one — and on a parachute,
  //    as desktop does; a mass the user typed on any other part stays;
  //  - an assembly the user weighed (the flag on a mass that is not a
  //    catalogue mass) stays whole either way: one part changing inside it does
  //    not change what they weighed, and desktop keeps it too.
  // A weighing is a finite mass (audit row 522): a NaN one is no override to keep.
  const held = prior ? numOpt(prior.node, 'overrideMass') : undefined;
  const heldIsCatalogue = prior != null && holdsCatalogueMass(prior.node, prior.presets);
  const weighedAssembly = type !== 'parachute' && held !== undefined && !heldIsCatalogue
    && prior?.node['overrideSubcomponentsMass'] === true;
  if (!weighedAssembly && p.mass !== undefined && p.mass > 0) {
    set('overrideMass', p.mass);
    own('overrideSubcomponentsMass', undefined);
  } else if (!weighedAssembly && (type === 'parachute' || heldIsCatalogue)) {
    own('overrideMass', undefined);
    own('overrideSubcomponentsMass', undefined);
  }
  // The catalogue identity rides with the part, so a saved file names the row
  // it came from (.rkt <PartMfg>/<PartNo>, .ork <preset>) and an import can
  // find it again.
  set('presetManufacturer', p.manufacturer);
  set('presetPartNo', p.partNo);
  // A pick is a new link, so desktop's own link for the part it replaces (an
  // .ork's <preset>, carried for the next save) names the wrong row now.
  for (const key of Object.values(ORK_PRESET_KEYS)) own(key, undefined);

  const out = n(p, 'outsideDiameter');
  const inn = n(p, 'insideDiameter');
  /**
   * A row that names a shape brings that shape's DEFAULT parameter with it, and
   * (transitions) its default clipping — desktop's Transition.loadFromPreset
   * calls setShapeParameter(s.defaultParameter()) and setClipped(s.canClip).
   * Left alone, a 0.5 power-series parameter from the previous part rode onto
   * the catalogue's ogive, which reads it as a secant ogive: a different shape.
   * `undefined` is the kernel's own "setShapeType's default" (ComponentFactory).
   */
  const setShape = () => {
    if (typeof p['shape'] !== 'string') return;
    set('shape', (p['shape'] as string).toLowerCase());
    own('shapeParameter', undefined);
    if (type === 'transition') own('clipped', undefined);
  };
  switch (type) {
    case 'bodytube':
    case 'tubecoupler':
    case 'innertube':
      set('length', n(p, 'length'));
      set('outerRadius', half(out));
      if (out !== undefined && inn !== undefined) set('thickness', (out - inn) / 2);
      break;
    case 'nosecone':
      set('length', n(p, 'length'));
      set('aftRadius', half(out));
      setShape();
      // Solid or hollow is part of the part: a row that does not say solid
      // describes a hollow shell (every shipped nose row either says
      // `filled: true` or states a wall thickness, measured 2026-09-22, and
      // desktop's SymmetricComponent.loadFromPreset sets filled = false on a
      // THICKNESS). Writing only `true` left a solid cone's flag on the next,
      // hollow, part — the 975.8 g thin-wall nose above.
      own('filled', p['filled'] === true);
      set('shoulderRadius', half(n(p, 'shoulderDiameter')));
      set('shoulderLength', n(p, 'shoulderLength'));
      set('thickness', n(p, 'thickness'));
      break;
    case 'transition':
      set('length', n(p, 'length'));
      set('foreRadius', half(n(p, 'foreOutsideDiameter')));
      set('aftRadius', half(n(p, 'aftOutsideDiameter')));
      setShape();
      // A balsa reducer is solid. Until v0.097 only the nose-cone branch honoured
      // `filled`, so every one of the 314 catalogue transitions marked solid and
      // carrying no catalogue mass applied as a hollow 2 mm shell - measured
      // 1.129 g against 5.026 g on one SEMROC part, a 4.5x mass error. Ruled
      // 2026-09-03: "Fix it." And a hollow row writes `false`, for the reason
      // given on the nose-cone branch.
      own('filled', p['filled'] === true);
      set('foreShoulderRadius', half(n(p, 'foreShoulderDiameter')));
      set('foreShoulderLength', n(p, 'foreShoulderLength'));
      set('aftShoulderRadius', half(n(p, 'aftShoulderDiameter')));
      set('aftShoulderLength', n(p, 'aftShoulderLength'));
      set('thickness', n(p, 'thickness'));
      break;
    case 'centeringring':
    case 'bulkhead':
      set('length', n(p, 'length'));
      break;
    case 'engineblock':
      set('length', n(p, 'length'));
      // The catalogue OD is applied, exactly as the tubecoupler branch above
      // does and as desktop does: ThicknessRingComponent.loadFromPreset:21-36
      // sets outerRadiusAutomatic = false and outerRadius = OD/2 whenever the
      // row has an OUTER_DIAMETER. Without it a catalogue engine block took the
      // kernel's AUTOMATIC radius - the parent tube's inner radius - while the
      // very next line read the row's own outsideDiameter to compute the wall
      // and then threw the diameter away. That was invisible while the bridge
      // set the wall pre-attach, because the clamp made the part weigh 0 g
      // whatever its radius; now that the wall is real, the radius has to be
      // the catalogued one or a thrust ring reads its airframe's bore instead
      // of its own.
      set('outerRadius', half(out));
      if (out !== undefined && inn !== undefined) set('thickness', (out - inn) / 2);
      break;
    case 'launchlug':
      set('length', n(p, 'length'));
      set('outerRadius', half(out));
      if (out !== undefined && inn !== undefined) set('thickness', (out - inn) / 2);
      break;
    case 'parachute': {
      // Every canopy field below is OWNED — desktop's Parachute.loadFromPreset
      // resets each one the row lacks to its default (diameter, Cd → automatic
      // 0.8, line count 6, line length 0.3 m, both materials), and so does this.
      const pos = (v: number | undefined) => (v !== undefined && v > 0 ? v : undefined);
      own('diameter', pos(n(p, 'diameter')));
      // Manufacturer-rated canopy Cd — referenced to the canopy area MINUS the
      // spill hole, not the nominal diameter (see the hole, below). Dropping
      // this silently falls back to the kernel default 0.8 — a
      // Fruity Chutes Iris Ultra (Cd 2.2) then descends 1.66× too fast. A row
      // with no rated Cd (217 of 473, measured 2026-09-22) flies that default,
      // NOT the previous canopy's rating.
      own('cd', pos(n(p, 'dragCoefficient')));
      // A canopy's Cd and its spill hole are ONE fact. Fruity Chutes (and the
      // rest) quote a Cd referenced to the canopy area MINUS the vent; the
      // kernel works from the nominal diameter and scales by 1 − (d/D)², which
      // is the same area. Taking the Cd and dropping the hole reads 1.5–2 %
      // slow on every vented canopy — so they travel together, and a row with
      // no vent (188 rows carry a Cd and no vent) CLEARS the last canopy's, or
      // its Cd would be flown against somebody else's hole.
      own('spillHoleDiameter', n(p, 'spillHoleDiameter'));
      own('lineCount', pos(n(p, 'lineCount')));
      own('lineLength', pos(n(p, 'lineLength')));
      const surf = p.material?.type === 'SURFACE' ? p.material : undefined;
      own('surfaceMaterialName', surf?.name);
      own('surfaceDensity', surf?.density);
      own('lineMaterialName', p.lineMaterial?.name);
      own('lineDensity', p.lineMaterial?.density);
      break;
    }
    case 'streamer': {
      set('stripLength', n(p, 'length'));
      set('stripWidth', n(p, 'width'));
      // Owned like the canopy's: no rated Cd means the kernel's automatic
      // streamer Cd, which is what desktop's Streamer.loadFromPreset restores
      // (cdAutomatic = true) on every preset.
      const scd = n(p, 'dragCoefficient');
      own('cd', scd !== undefined && scd > 0 ? scd : undefined);
      const surf = p.material?.type === 'SURFACE' ? p.material : undefined;
      own('surfaceMaterialName', surf?.name);
      own('surfaceDensity', surf?.density);
      break;
    }
    // No other type has a catalogue (KIND_FOR_TYPE), so a pick carries only
    // the identity and mass set above.
    default:
      break;
  }
  return patch;
}

// ---------------- CSV round-trip ----------------

/**
 * `bodytube` is not a kind. Every picker and the recovery sizer match kind by
 * exact string (`p.kind === 'Parachute'`), so a lower-case row imported, was
 * counted a success, and then appeared nowhere at all. Derived from
 * KIND_FOR_TYPE so there is one list of kinds and not two; an unrecognised
 * kind passes through as typed, exactly as before (2026-09-21).
 */
const CANONICAL_KIND = new Map(
  Object.values(KIND_FOR_TYPE).filter((k): k is string => !!k).map((k) => [k.toLowerCase(), k]),
);

/**
 * Measured over the shipped presets.json (2026-09-21): material type is a pure
 * function of kind — Parachute 473/473 and Streamer 67/67 SURFACE, and no row
 * outside those two kinds is SURFACE; of the other 4,190, 4,165 are BULK and 25
 * carry no material object at all (4,730 rows in all).
 *
 * So a blank materialType cell is filled from the KIND rather than assumed
 * BULK, which on a canopy threw the fabric weight away: `presetPatch` writes
 * `surfaceDensity` only for a SURFACE material, and the bulk `density` it
 * wrote instead reaches nothing — `ComponentFactory` applies a density only to
 * an External or Structural component and a Parachute is neither — so the
 * canopy arrived weightless rather than wrongly weighted.
 */
const SURFACE_KINDS = new Set(['Parachute', 'Streamer']);

/**
 * The material type a kind's rows carry, and the only one presetPatch applies
 * to it: SURFACE on a canopy or streamer, BULK on anything else. A row typed
 * otherwise would label the part with its material and weigh it with the old
 * one, so PresetPicker refuses it (review of the audit fixes, 2026-10-01).
 */
export function materialTypeFor(kind: string): 'SURFACE' | 'BULK' {
  return SURFACE_KINDS.has(kind) ? 'SURFACE' : 'BULK';
}

const CSV_COLS = [
  'kind', 'manufacturer', 'partNo', 'description', 'materialName', 'materialType',
  'materialDensity', 'mass', 'length', 'outsideDiameter', 'insideDiameter', 'shape',
  'filled', 'shoulderDiameter', 'shoulderLength', 'thickness', 'foreOutsideDiameter',
  'aftOutsideDiameter', 'foreShoulderDiameter', 'foreShoulderLength',
  'aftShoulderDiameter', 'aftShoulderLength', 'diameter', 'dragCoefficient',
  'spillHoleDiameter', 'packedDiameter', 'packedLength', 'lineCount', 'lineLength', 'width',
  'lineMaterialName', 'lineMaterialDensity',
];

export function presetsToCsv(presets: Preset[]): string {
  const rows = [CSV_COLS.join(',')];
  for (const p of presets) {
    const flat: Record<string, unknown> = {
      ...p,
      materialName: p.material?.name,
      materialType: p.material?.type,
      materialDensity: p.material?.density,
      lineMaterialName: p.lineMaterial?.name,
      lineMaterialDensity: p.lineMaterial?.density,
    };
    rows.push(CSV_COLS.map((c) => csvCell(flat[c])).join(','));
  }
  return rows.join('\n') + '\n';
}

/**
 * Full-text CSV parser: records split on unquoted newlines (a quoted cell
 * may contain commas, quotes AND newlines — presetsToCsv writes all three).
 */
function parseCsv(csv: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let cur = '';
  let quoted = false;
  for (let i = 0; i < csv.length; i++) {
    const ch = csv[i]!;
    if (quoted) {
      if (ch === '"' && csv[i + 1] === '"') { cur += '"'; i++; }
      else if (ch === '"') quoted = false;
      else cur += ch;
    } else if (ch === '"') quoted = true;
    else if (ch === ',') { row.push(cur); cur = ''; }
    else if (ch === '\n' || ch === '\r') {
      if (ch === '\r' && csv[i + 1] === '\n') i++;
      row.push(cur); cur = '';
      rows.push(row); row = [];
    } else cur += ch;
  }
  if (cur !== '' || row.length > 0) { row.push(cur); rows.push(row); }
  return rows.filter((r) => r.some((c) => c.trim() !== ''));
}

/** Parses an edited CSV back into presets (SI values, same columns as export). */
export function csvToPresets(csv: string): Preset[] {
  const records = parseCsv(csv);
  if (records.length < 2) return [];
  const header = records[0]!.map((h) => h.trim());
  const out: Preset[] = [];
  for (const cells of records.slice(1)) {
    const row: Record<string, string> = {};
    // csvCell prefixes ONE apostrophe to a cell a spreadsheet would read as a
    // formula (see csvUtil.ts). Strip exactly one back off, or a preset this app
    // exported and re-imported comes back with a literal ' on its part number.
    // Numeric columns are unaffected: Number("'-1") is NaN either way.
    header.forEach((h, i) => { row[h] = (cells[i] ?? '').replace(/^'/, ''); });
    if (!row['kind'] || !row['partNo']) continue;
    const p: Preset = {
      kind: CANONICAL_KIND.get(row['kind']!.trim().toLowerCase()) ?? row['kind']!.trim(),
      manufacturer: row['manufacturer'] || 'Custom',
      partNo: row['partNo']!,
      description: row['description'] ?? '',
    };
    // A non-numeric density is left AS PARSED, deliberately. PresetPicker's
    // rowIsSound refuses the row and names its part number, so the user can go
    // and fix it; dropping the material here instead would import the row clean
    // and silently weightless, which is the failure this was meant to stop.
    // A HALF-FILLED PAIR goes the same way (2026-09-21): `&&` here meant a
    // name with no density skipped the material block entirely and imported as
    // a clean success, so the part kept its old weight under a new label —
    // exactly the silent case the paragraph above refuses.
    // A missing NAME COLUMN is the same half pair (audit 2026-09-22): the cell
    // is undefined, not '', and a `name` of undefined made rowIsSound's
    // `.trim()` throw, so the whole import failed naming no row. `?? ''` keeps
    // the declared string type, and the empty name is refused and named.
    if (row['materialName'] || row['materialDensity']) {
      p.material = {
        name: row['materialName'] ?? '',
        // Trimmed and upper-cased to the catalogue's own spelling, as `kind` is
        // above (audit 2026-09-30). presetPatch tests `=== 'SURFACE'` and
        // `=== 'BULK'`, so a typed `surface` passed rowIsSound and then wrote no
        // fabric weight, and a lone space was not blank. Blank takes the kind's.
        type: (row['materialType'] ?? '').trim().toUpperCase() || materialTypeFor(p.kind),
        density: Number(row['materialDensity']),
      };
    }
    if (row['lineMaterialName'] || row['lineMaterialDensity']) {
      p.lineMaterial = {
        name: row['lineMaterialName'] ?? '',
        type: 'LINE',
        density: Number(row['lineMaterialDensity']),
      };
    }
    for (const c of CSV_COLS) {
      if (['kind', 'manufacturer', 'partNo', 'description', 'materialName', 'materialType', 'materialDensity', 'shape', 'filled', 'lineMaterialName', 'lineMaterialDensity'].includes(c)) continue;
      // TRIM BEFORE TESTING. `Number(' ')` is 0 and `' ' !== ''`, so a cell a
      // spreadsheet left holding a single space imported as the NUMBER ZERO —
      // a zero mass (which used to become `overrideMass: 0`), a zero diameter,
      // a zero length — rather than being skipped as the blank it is.
      // DECIMAL ONLY (seam review of audit 2026-09-22): `Number` also read
      // "0x10" as 16 and "0b110" as 6 — a 16 m canopy from a typo — where every
      // design-file reader refuses them (parseDecimal). A refused cell is blank.
      const raw = (row[c] ?? '').trim();
      const v = parseDecimal(raw);
      if (raw !== '' && Number.isFinite(v)) p[c] = v;
    }
    // The shape and the solid flag the same way (audit 2026-09-30). A
    // spreadsheet saves a `true` cell back as `TRUE` (Excel does), and an exact
    // match read every solid nose cone and balsa transition in an edited export
    // as a hollow shell. A padded shape reached the kernel as a name it does
    // not know, which it flies as an ogive, and a lone space overwrote the
    // part's shape on a pick where a blank cell leaves it alone.
    const shape = (row['shape'] ?? '').trim();
    if (shape) p['shape'] = shape.toUpperCase();
    if (/^\s*true\s*$/i.test(row['filled'] ?? '')) p['filled'] = true;
    out.push(p);
  }
  return out;
}

// ---------------------------------------------------------------------------
// Catalogue links on import (ruled 2026-09-03)
// ---------------------------------------------------------------------------

/**
 * A part an importer read together with the catalogue identity the file gave
 * it — RockSim's <PartMfg>/<PartNo>, desktop's <preset manufacturer partno>.
 * Resolved once the whole tree is built (applyPresetLinks), so "the file left
 * it unset" is judged against everything the file said about the part.
 */
export interface PendingPresetLink {
  node: ComponentNode;
  manufacturer: string;
  partNo: string;
}

/** The lookup key the preset pipeline dedupes on: kind | manufacturer | part number. */
const linkKey = (kind: string, manufacturer: unknown, partNo: unknown): string =>
  `${kind}|${mfrKey(manufacturer)}|${partKey(partNo)}`;

/** Every part number a row answers to: its own, and those of the duplicates it absorbed. */
const partNumbersOf = (p: Preset): unknown[] =>
  [p.partNo, ...(Array.isArray(p['altPartNos']) ? (p['altPartNos'] as unknown[]) : [])];

/**
 * Is this node's mass override the catalogue mass of the part it is linked to
 * — one `presetPatch` wrote, or a file copied from the same row — rather than a
 * weight the user typed? `presetPatch` clears the first kind on a pick and
 * never the second (review of audit 2026-09-22: clearing every override threw
 * away a user's weighed mass on 1,197 of the 1,308 body-tube rows, which carry
 * none). Matched on the key applyPresetLinks matches on, alternate part numbers
 * included, and to 0.01 % so a mass that has been through a saved file still
 * reads as the catalogue's (a user who typed the catalogue's own figure has, in
 * effect, kept the catalogue's mass, and it goes with that part).
 *
 * A PART DETACH HAS UNLINKED still holds that mass — Detach keeps every value
 * — and it is still the old part's catalogue weight (wave 3 verifier: Apogee
 * 10063's 5.8 g, detached, rode onto a re-picked tube that has no catalogue
 * mass). With the link gone, the part is matched by the name the pick gave it,
 * "<manufacturer> <part number>". A part renamed since is the user's, and so is
 * its mass: kept, as a typed one is.
 */
export function holdsCatalogueMass(node: ComponentNode, presets: readonly Preset[]): boolean {
  // Finite (audit row 522): a NaN passed a typeof test and then failed the
  // tolerance test below in the direction that says "catalogue mass" — a NaN
  // difference is never greater than anything.
  const held = numOpt(node, 'overrideMass');
  const kind = KIND_FOR_TYPE[node.type];
  if (held === undefined || !kind) return false;
  const weighsAsRow = (p: Preset) => p.kind === kind && typeof p.mass === 'number' && p.mass > 0
    && Math.abs(held - p.mass) <= 1e-4 * p.mass;
  if (node['presetPartNo'] == null) {
    const name = typeof node.name === 'string' ? node.name.trim() : '';
    return name !== '' && presets.some((p) => weighsAsRow(p) && `${p.manufacturer} ${p.partNo}` === name);
  }
  const want = linkKey(kind, node['presetManufacturer'], node['presetPartNo']);
  return presets.some((p) => weighsAsRow(p)
    && partNumbersOf(p).some((pn) => linkKey(kind, p.manufacturer, pn) === want));
}

// ---------------------------------------------------------------------------
// The conflict marker (approved 2026-09-07)
// ---------------------------------------------------------------------------

/**
 * How far apart a part's figure and its catalogue row's must be before the
 * difference could matter. Two numbers differ when |a − b| exceeds the larger
 * of `abs` (SI) and `rel` × the larger of the two; text and flags differ when
 * they are not the same (text trimmed and case-blind).
 */
export interface CatalogueTolerance {
  abs?: number;
  rel?: number;
}

/** One field as the conflict marker reads it. */
export interface CatalogueField {
  /** Plain words — the import note's, and the Catalogue line's: "line count", never "lineCount". */
  words: string;
  /** How a difference is judged, or null where the field is never compared (the reason is on its row). */
  differs: CatalogueTolerance | null;
}

/**
 * Along the part — a length, a shoulder's length: half a millimetre. The
 * design's own example of a difference not worth flagging is "a 0.1 mm
 * rounding difference in a shoulder length", and lengths are commonly
 * published to a sixty-fourth of an inch (0.40 mm; the .orc files have an
 * in/64 unit for it), so a typed or converted copy of the same figure can be
 * that far off; past it the part is a different length.
 */
const ALONG: CatalogueTolerance = { abs: 0.0005 };
/**
 * Across the part — a radius, a wall: a tenth of a millimetre. Parts are
 * fitted to each other by these, and catalogues commonly state them to a
 * thousandth of an inch (0.025 mm): a typed copy rounds well inside 0.1 mm,
 * and 0.2 mm on a diameter is already the difference between a coupler that
 * slides in and one that does not.
 */
const ACROSS: CatalogueTolerance = { abs: 0.0001 };
/**
 * Recovery hardware — a canopy, its vent, its lines, a streamer: 1 %, and
 * never less than 2 mm. They are sold in whole or half inches and measured
 * with a tape; 1 % of a 36 in canopy is 9 mm, wider than any rounding of a
 * typed figure and narrower than the step to the next size (a 34 in canopy is
 * 5.6 % smaller), and a sixteenth of an inch (1.6 mm) on a vent is not a
 * different vent.
 */
const RECOVERY: CatalogueTolerance = { abs: 0.002, rel: 0.01 };
/**
 * A material's density: 1 %. Densities are published to three significant
 * figures; a real change of material is far outside it — cardboard against
 * phenolic is 39 %. Compared only while the density decides the part's weight
 * (`weighsByDensity`).
 */
const DENSITY: CatalogueTolerance = { rel: 0.01 };
/** Text and flags: the same or not. */
const SAME: CatalogueTolerance = {};

const NEVER = null;

/**
 * THE CONFLICT MARKER'S ONE TABLE — every field a catalogue pick can write
 * (`presetPatch`), in words, with how a difference in it is judged. The three
 * tiers of the approved design (docs/testing/response-2026-09-03b.md §3,
 * approved 2026-09-07) all read it: the import note (`applyPresetLinks`), and
 * the property panel's ≠ chip and Catalogue line (`catalogueDifferences`) — so
 * the note at open and the markers afterwards cannot disagree about what
 * counts as a difference. The design's refinement, verbatim: "only flag a
 * difference that could matter — a Cd, a diameter, a mass, a line count. Not
 * a 0.1 mm rounding difference in a shoulder length. Set the threshold per
 * field rather than one global epsilon." Tier (a) shipped (v0.115) with one
 * 0.5 % epsilon for every number and a word list that missed a transition's
 * four shoulder keys, which reached a user raw ("foreShoulderRadius") in the
 * import note for 2,4-D.rkt; services/presets.test.ts now requires every key
 * a pick can write to be named here.
 *
 * NOT COMPARED, and why — a row with `differs: NEVER`:
 *  - the part's name: the user's; the catalogue's is only a pick's default;
 *  - the link itself (manufacturer, part number);
 *  - a material's NAME: a label — the density beside it is the physics, and is
 *    compared on its own row, so the same figure under another name is not a
 *    difference that could matter;
 *  - a shape parameter, a transition's clipping and the "everything inside"
 *    mass flag: a pick only ever resets these to the default, so the catalogue
 *    states no figure to hold a part to.
 * A lookupTable: the keys it is asked about come off nodes a file wrote.
 */
const CATALOGUE_FIELDS: Record<string, CatalogueField> = lookupTable<CatalogueField>({
  name: { words: 'name', differs: NEVER },
  presetManufacturer: { words: 'manufacturer', differs: NEVER },
  presetPartNo: { words: 'part number', differs: NEVER },
  orkPresetManufacturer: { words: 'desktop OpenRocket’s manufacturer', differs: NEVER },
  orkPresetPartNo: { words: 'desktop OpenRocket’s part number', differs: NEVER },
  orkPresetDigest: { words: 'desktop OpenRocket’s preset digest', differs: NEVER },
  materialName: { words: 'material', differs: NEVER },
  surfaceMaterialName: { words: 'canopy material', differs: NEVER },
  lineMaterialName: { words: 'line material', differs: NEVER },
  shapeParameter: { words: 'shape parameter', differs: NEVER },
  clipped: { words: 'clipping', differs: NEVER },
  overrideSubcomponentsMass: { words: 'mass of everything inside', differs: NEVER },

  length: { words: 'length', differs: ALONG },
  shoulderLength: { words: 'shoulder length', differs: ALONG },
  foreShoulderLength: { words: 'fore shoulder length', differs: ALONG },
  aftShoulderLength: { words: 'aft shoulder length', differs: ALONG },
  outerRadius: { words: 'outer radius', differs: ACROSS },
  aftRadius: { words: 'base radius', differs: ACROSS },
  foreRadius: { words: 'fore radius', differs: ACROSS },
  thickness: { words: 'wall thickness', differs: ACROSS },
  shoulderRadius: { words: 'shoulder radius', differs: ACROSS },
  foreShoulderRadius: { words: 'fore shoulder radius', differs: ACROSS },
  aftShoulderRadius: { words: 'aft shoulder radius', differs: ACROSS },
  shape: { words: 'shape', differs: SAME },
  filled: { words: 'solid', differs: SAME },
  density: { words: 'material', differs: DENSITY },
  /**
   * A stated part mass. Catalogue masses are commonly published to 0.1 g or
   * to 0.01 oz (0.28 g) and converted: half a gram or 2 %, whichever is
   * larger, is the same part on a different scale. Only a mass the part STATES is compared
   * (`catalogueDifferences` has the rule) — never the computed one, and never
   * a weight on everything inside.
   */
  overrideMass: { words: 'mass', differs: { abs: 0.0005, rel: 0.02 } },

  diameter: { words: 'diameter', differs: RECOVERY },
  /**
   * Two published decimals (0.75, 1.5, 2.2): within half the last one it is
   * the same rated figure. A canopy's Cd is one fact with its spill hole and
   * is compared as a pair (`catalogueDifferences`, `applyPresetLinks`).
   */
  cd: { words: 'drag coefficient', differs: { abs: 0.005 } },
  spillHoleDiameter: { words: 'spill hole', differs: RECOVERY },
  /** A count has no rounding: one line either way is a different canopy. */
  lineCount: { words: 'line count', differs: { abs: 0.5 } },
  lineLength: { words: 'line length', differs: RECOVERY },
  surfaceDensity: { words: 'canopy material', differs: DENSITY },
  lineDensity: { words: 'line material', differs: DENSITY },
  stripLength: { words: 'strip length', differs: RECOVERY },
  stripWidth: { words: 'strip width', differs: RECOVERY },
});

/**
 * A TUBE CUT TO LENGTH IS NOT A DIFFERENCE. Desktop's own rule: a body tube
 * and a launch lug keep their preset when their length changes (24.12
 * BodyComponent.setLength and LaunchLug.setLength never call clearPreset, and
 * BodyComponent says why: "BodyTube allows changing length without resetting
 * the preset"), because tubes are sold long and cut. An inner tube takes the
 * same body-tube catalogue (KIND_FOR_TYPE), so the same stock length. Measured
 * on the tester files on hand (2026-10-01) under tier (a)'s old single
 * epsilon: all 14 linked body and inner tubes among them (vb38-dragstudy02.rkt
 * and Level 3 Rocket 5.5) were reported as disagreeing on their length. A
 * coupler's length, a ring's thickness and a nose's length ARE the part, and
 * desktop clears the link on them.
 */
const CATALOGUE_FIELDS_BY_TYPE: Record<string, Record<string, CatalogueField>> = lookupTable<Record<string, CatalogueField>>({
  bodytube: { length: { words: 'length', differs: NEVER } },
  innertube: { length: { words: 'length', differs: NEVER } },
  launchlug: { length: { words: 'length', differs: NEVER } },
  // A transition's aft radius is not a base; the panel calls it "Aft radius".
  transition: { aftRadius: { words: 'aft radius', differs: ACROSS } },
});

/** How the conflict marker reads `key` on a part of `type`, or undefined for a key it does not know. */
export function catalogueField(type: string, key: string): CatalogueField | undefined {
  const byType = CATALOGUE_FIELDS_BY_TYPE[type];
  if (byType && Object.hasOwn(byType, key)) return byType[key];
  return CATALOGUE_FIELDS[key];
}

/** Whether a part's `have` and its catalogue row's `want` differ by more than `tol` allows. */
export function differsFromCatalogue(tol: CatalogueTolerance, have: unknown, want: unknown): boolean {
  if (typeof have === 'number' && typeof want === 'number') {
    const allowed = Math.max(tol.abs ?? 0, (tol.rel ?? 0) * Math.max(Math.abs(have), Math.abs(want)));
    return Math.abs(have - want) > allowed;
  }
  if (typeof have === 'string' && typeof want === 'string') {
    return have.trim().toLowerCase() !== want.trim().toLowerCase();
  }
  if (typeof have === 'boolean' && typeof want === 'boolean') return have !== want;
  return false;
}

/** Plain words for a field, for a note — the key itself only for one the table does not know. */
const wordsFor = (type: string, key: string): string => catalogueField(type, key)?.words ?? key;

/** Each material density, and the name that travels with it. */
const MATERIAL_NAME_KEY: ReadonlyMap<string, string> = new Map([
  ['density', 'materialName'], ['surfaceDensity', 'surfaceMaterialName'], ['lineDensity', 'lineMaterialName'],
]);
const DENSITY_KEYS: ReadonlySet<string> = new Set(MATERIAL_NAME_KEY.keys());

/**
 * A MATERIAL'S DENSITY MATTERS ONLY WHILE IT DECIDES THE WEIGHT. A part that
 * states its own mass flies that mass whatever its material, and a row that
 * states one is weighed by it (`presetPatch` writes it as the override), so on
 * either side the mass is the figure — compared on its own row — and the
 * density beside it changes nothing that flies. Measured on the corpus:
 * goblin-256.ork's Rocketarium nose states 145.6 kg/m³ against the row's HIPS
 * 950, because desktop derives a catalogued part's density from its mass
 * (ComponentPresetFactory: mass ÷ volume) where this catalogue keeps the
 * material and carries the mass — the same 76 g part, which "use 950" would
 * have made 6.5 times heavier; and a weighed canopy's fabric (4in WM Extreme.rkt,
 * 2,4-D.rkt) was flagged against a row whose canopy weighs what the file's does.
 */
const weighsByDensity = (node: ComponentNode, patch: Record<string, unknown>): boolean =>
  patch['overrideMass'] === undefined && numOpt(node, 'overrideMass') === undefined;

/** One difference between a linked part and its catalogue row. */
export interface CatalogueDifference {
  /** The field the marker sits on. */
  key: string;
  /** Plain words for it (catalogueField). */
  words: string;
  /** What the part flies: its own value, or a blank's. `undefined` is an automatic Cd. */
  have: number | string | boolean | undefined;
  /** The catalogue row's figure. */
  want: number | string | boolean;
  /**
   * The edit that takes the catalogue's figure — the field alone, or with the
   * other half of its fact: a canopy's Cd and spill hole, a material's density
   * and name, a shape and its default parameter.
   */
  patch: Partial<ComponentNode>;
}

/**
 * What a field flies when the part leaves it blank, where that is one known
 * value — the kernel's default shape and solidity, and schema.ts `blankValue`
 * (a canopy's 6 lines, no vent, an empty shoulder) — or undefined.
 */
function flown(node: ComponentNode, key: string): number | string | boolean | undefined {
  const v = node[key];
  if (typeof v === 'string' || typeof v === 'boolean') return v;
  const n = numOpt(node, key);
  if (n !== undefined) return n;
  if (key === 'filled') return false;
  // ComponentFactory's own: str(node, "shape", "ogive") / "conical".
  if (key === 'shape') return node.type === 'transition' ? 'conical' : 'ogive';
  return blankValue(node.type, key);
}

/**
 * Every field where a part linked to the catalogue now differs from its row —
 * by enough to matter, under the one table above — for the property panel's ≠
 * chips (tier b) and its Catalogue line (tier c). Live: it reads what the part
 * flies now, so a field the user cleared is held against the catalogue too,
 * where the import note (tier a) compares only what a file stated.
 *
 * Three facts are compared whole, never by halves:
 *  - A CANOPY'S Cd AND ITS SPILL HOLE (the standing Fruity Chutes ruling: the
 *    maker's Cd is referenced to the vented area). Either half off the row's
 *    is a difference, and taking either takes both. A row with no rated Cd
 *    states no pair, so neither half is compared. A part flying the automatic
 *    Cd against a rated one differs (`have` undefined).
 *  - A MATERIAL: compared by density while the density decides the weight
 *    (`weighsByDensity`), and taken with its name.
 *  - A SHAPE: taken with its default parameter, as a pick does.
 *
 * A MASS only where the part states one for itself (`overrideMass`, without
 * "everything inside"): the computed mass is the geometry's, and the
 * catalogue's stock mass is a different claim about a different number.
 */
export function catalogueDifferences(node: ComponentNode, row: Preset): CatalogueDifference[] {
  const patch = presetPatch(node.type, row) as Record<string, unknown>;
  const out: CatalogueDifference[] = [];
  const isCanopy = node.type === 'parachute';
  const byDensity = weighsByDensity(node, patch);
  for (const [key, want] of Object.entries(patch)) {
    if (!(typeof want === 'number' || typeof want === 'string' || typeof want === 'boolean')) continue;
    const field = catalogueField(node.type, key);
    if (!field?.differs) continue;
    if (isCanopy && (key === 'cd' || key === 'spillHoleDiameter')) continue; // the pair, below
    if (DENSITY_KEYS.has(key) && !byDensity) continue;
    let have = flown(node, key);
    if (key === 'overrideMass') {
      if (node['overrideSubcomponentsMass'] === true) continue;
      have = numOpt(node, 'overrideMass');
      if (have === undefined) continue;
    }
    // A blank Cd is the AUTOMATIC one, which a rated figure is meant to replace.
    const autoCd = key === 'cd' && have === undefined;
    if (!autoCd && (have === undefined || !differsFromCatalogue(field.differs, have, want))) continue;
    const take: Record<string, unknown> = { [key]: want };
    // A material is taken whole, its name with its density …
    const nameKey = MATERIAL_NAME_KEY.get(key);
    if (nameKey) take[nameKey] = patch[nameKey];
    // … and a shape with its default parameter (and a transition's clipping),
    // exactly as a pick takes it.
    if (key === 'shape') {
      take['shapeParameter'] = undefined;
      if ('clipped' in patch) take['clipped'] = undefined;
    }
    out.push({ key, words: field.words, have, want, patch: take as Partial<ComponentNode> });
  }
  const cd = numOpt(patch, 'cd');
  if (isCanopy && cd !== undefined) {
    // No vent on the row is a whole fact — an unvented canopy — and flies as none.
    const vent = numOpt(patch, 'spillHoleDiameter') ?? 0;
    const both: Partial<ComponentNode> = { cd, spillHoleDiameter: patch['spillHoleDiameter'] };
    const haveCd = numOpt(node, 'cd');
    const haveVent = numOpt(node, 'spillHoleDiameter') ?? 0;
    if (haveCd === undefined || differsFromCatalogue(catalogueField('parachute', 'cd')!.differs!, haveCd, cd)) {
      out.push({ key: 'cd', words: wordsFor('parachute', 'cd'), have: haveCd, want: cd, patch: both });
    }
    if (differsFromCatalogue(catalogueField('parachute', 'spillHoleDiameter')!.differs!, haveVent, vent)) {
      out.push({ key: 'spillHoleDiameter', words: wordsFor('parachute', 'spillHoleDiameter'), have: haveVent, want: vent, patch: both });
    }
  }
  return out;
}

/**
 * The catalogue row a part is linked to, or undefined: no link, or a row this
 * browser does not have (a user's CSV preset from another browser, a row since
 * curated away). Matched the way `applyPresetLinks` matches a file's part —
 * the alias table, part-number normalisation, absorbed part numbers — and the
 * first row to answer wins, as there.
 */
export function linkedPreset(node: ComponentNode, presets: readonly Preset[]): Preset | undefined {
  const kind = KIND_FOR_TYPE[node.type];
  if (!kind || typeof node['presetPartNo'] !== 'string') return undefined;
  const want = linkKey(kind, node['presetManufacturer'], node['presetPartNo']);
  return presets.find((p) => p.kind === kind
    && partNumbersOf(p).some((pn) => linkKey(kind, p.manufacturer, pn) === want));
}

/** Every key that makes up a part's catalogue link — Detach clears these, and nothing else. */
export const CATALOGUE_LINK_KEYS: readonly string[] = [
  'presetManufacturer', 'presetPartNo', ...Object.values(ORK_PRESET_KEYS),
];

/**
 * Tier (c)'s Detach as an edit: the link goes, and the markers with it, and
 * every value on the part stays exactly as it is — desktop's own "editing a
 * dimension clears the preset", done on purpose. An ordinary tree edit, so
 * undo puts the link back; nothing records that it happened.
 */
export function detachPatch(): Partial<ComponentNode> {
  return Object.fromEntries(CATALOGUE_LINK_KEYS.map((k) => [k, undefined]));
}

/**
 * Link imported parts to the catalogue. The owner's ruling (2026-09-03): "if a
 * file is imported and the parachute in the file does match a chute in our
 * parts database, we should import the settings from our database."
 *
 * PRECEDENCE. The file's explicit values stand; the catalogue fills only what
 * the file left unset — a foreign file: in one this app wrote it fills nothing
 * (`opts.ownFile`). That is desktop OpenRocket's own order — its saver writes
 * <preset> first and every explicit element after it, so the explicit values win
 * on load — and it is the rule that does not snap a body tube the author cut to
 * length back to the catalogue's stock length. For a RockSim chute the unset
 * field is exactly the one that matters: its <DragCoefficient>0.75 is the
 * "auto" sentinel, which the importer does not pin, so the catalogue's real Cd
 * lands here (2.2 on a Fruity Chutes toroidal against the kernel default 0.8 —
 * the difference between failing and passing the 20 ft/s landing check on a
 * correctly built rocket).
 *
 * THE MASS IS NEVER TAKEN FROM THE CATALOGUE. RockSim keeps <PartNo> on a part
 * the author has since cut down, so a stock mass would land on a shortened
 * tube; the file's own mass model (density × geometry, or its measured mass) is
 * the author's and stays. Desktop clears its preset link the moment a dimension
 * is edited, which is why the same hazard does not arise for .ork.
 *
 * Returns how many parts were linked; appends one plain-language note.
 */
export function applyPresetLinks(
  pending: readonly PendingPresetLink[],
  presets: readonly Preset[] | undefined,
  notes: string[],
  opts?: {
    /**
     * A FILE THIS APP WROTE — an .ork carrying its creator stamp: a save, a
     * share link, the autosave recovery file. A blank in it is the user's own,
     * not a gap: an automatic Cd they went back to while the ≠ marker sat
     * beside it, a vent they took out. So each part is linked and nothing
     * else: the catalogue fills nothing, and nothing is said, because a
     * difference the user kept is not news at every open (the owner's
     * constraint on the conflict marker, issues-2026-09-03b: "we don't want to
     * nag them every time they open the file if they decide to override the
     * default catalogue values"). The property panel's markers show it. Filled,
     * a save and reopen changed the design (wave 3 verifier): b2 Rocketry
     * CL-24-N with its Cd cleared came back flying the rated 1.16.
     */
    ownFile?: boolean;
  },
): number {
  if (!presets?.length || pending.length === 0) return 0;
  const byKey = new Map<string, Preset>();
  for (const p of presets) {
    const k = linkKey(p.kind, p.manufacturer, p.partNo);
    if (!byKey.has(k)) byKey.set(k, p);
    // A row can answer to part numbers it has absorbed. The ten RockSim Fruity
    // Chutes rows were dropped as duplicates on 2026-09-03, but `.rkt` FILES
    // still name them — Eric's own Wildman carries <PartNo>29185</PartNo> — so
    // the numbers ride on the surviving row. Dropping a duplicate must never
    // cost a file its catalogue link.
    const alts = p['altPartNos'];
    if (Array.isArray(alts)) {
      for (const alt of alts) {
        const ak = linkKey(p.kind, p.manufacturer, alt);
        if (!byKey.has(ak)) byKey.set(ak, p);
      }
    }
  }
  const lines: string[] = [];
  /** Tier (a) of the conflict marker: one line per part whose stated values disagree with its row. */
  const conflictLines: string[] = [];
  let linked = 0;
  for (const { node, manufacturer, partNo } of pending) {
    const kind = KIND_FOR_TYPE[node.type];
    if (!kind) continue;
    const p = byKey.get(linkKey(kind, manufacturer, partNo));
    if (!p) continue;
    if (opts?.ownFile) {
      node['presetManufacturer'] = p.manufacturer;
      node['presetPartNo'] = p.partNo;
      linked += 1;
      continue;
    }
    const patch = presetPatch(node.type, p) as Record<string, unknown>;
    const filled = new Set<string>();
    // THE CANOPY PAIR IS EXEMPT FROM THE PER-KEY GATE BELOW.
    //
    // A rated Cd and its spill hole are ONE fact (standing ruling, 2026-09-03):
    // the maker measures Cd against the canopy area MINUS the vent, and the
    // kernel re-derives that same area as 1 − (d/D)² of the nominal disc. Filling
    // them independently grafts the catalogue's half onto the file's half. The
    // real case: a .rkt naming Fruity Chutes CFC-015-N whose author typed their
    // own 1.5 in vent on the 15 in canopy. RockSim's <DragCoefficient>0.75 is the
    // "auto" sentinel the importer does not pin, so `cd` was unset and the
    // catalogue's 1.5 landed — a figure measured against the maker's 20 % vent —
    // while the file's own 10 % vent stayed, applying 0.99 where 0.96 was meant:
    // CdA 3.1 % high, descent rate 1.5 % LOW, which is the optimistic direction.
    //
    // So the pair moves together or not at all, and that holds in REVERSE too:
    // the catalogue's vent never lands on a Cd the file stated. A row with no
    // `spillHoleDiameter` is a whole fact (an unvented canopy) and may still
    // supply its Cd; a row with a vent but no Cd is half of one, and supplies
    // neither.
    // Only a CANOPY has the pair: a streamer's Cd is referenced to strip area
    // and it has no vent, so it keeps the plain per-key gate below.
    const isCanopy = node.type === 'parachute';
    const PAIR = ['cd', 'spillHoleDiameter'] as const;
    const canopyStatesHalf = isCanopy && PAIR.some((k) => node[k] !== undefined);
    const takePair = patch['cd'] !== undefined && !canopyStatesHalf;
    /**
     * A WALL THICKNESS IS A STATEMENT THAT THE PART IS HOLLOW (audit 2026-09-22).
     * The .ork reader marks a solid part `filled: true` and a hollow one only by
     * its numeric <thickness> — desktop's own setThickness clears `filled` — so
     * "filled is unset" on such a node is not "the file left it unset". Before
     * this, the catalogue's `filled: true` landed on hollow noses a file had
     * modelled with a wall: 19.6 g → 107.8 g (Rocketarium HIPS) and 103.1 g →
     * 907.4 g (Madcow 2.6" fiberglass), overstating stability, from any file.
     * Read as `filled: false` for both the fill and the conflict marker. (The
     * RockSim reader now writes the `false` itself; this covers every reader.)
     */
    const statesHollow = (node.type === 'nosecone' || node.type === 'transition')
      && node['filled'] === undefined && numOpt(node, 'thickness') !== undefined;
    const stated = (key: string): unknown => (key === 'filled' && statesHollow ? false : node[key]);
    /**
     * THE CONFLICT MARKER, tier (a) — the owner's caveat on the precedence
     * ruling (issues-2026-09-03b.md:26: *"in the case where file's explicit
     * values are in conflict with catalogue values, should we warn the user?
     * … we don't want to nag them"*), approved 2026-09-07. The file's value
     * STANDS — that is the ruling and it does not change here — but where it
     * disagrees with the catalogue row it was matched to, the note says so,
     * once, in one sentence. Nothing is stored and nothing is dismissed: the
     * only ways to make it go away are real edits that already persist.
     *
     * Read BEFORE any assignment in the loop below, so it only ever compares
     * a value the file stated with the catalogue's — never a value this loop
     * just filled in. The canopy pair is compared only when the file states
     * BOTH halves: half a pair against a whole one is not a disagreement about
     * the same fact.
     *
     * WHAT counts as a disagreement, and the words for it, are the conflict
     * marker's one table (catalogueField), which the property panel's ≠ chips
     * read too — so the note at open and the markers afterwards agree. A mass
     * is compared where the file states one for the part itself; it is still
     * never TAKEN (the fill loop below).
     */
    const conflicts: string[] = [];
    const byDensity = weighsByDensity(node, patch);
    for (const [key, value] of Object.entries(patch)) {
      if (value === undefined) continue;
      const field = catalogueField(node.type, key);
      if (!field?.differs) continue;
      const have = stated(key);
      if (have === undefined) continue;
      if (isCanopy && (key === 'cd' || key === 'spillHoleDiameter')
        && !PAIR.every((k) => node[k] !== undefined)) continue;
      if (key === 'overrideMass' && node['overrideSubcomponentsMass'] === true) continue;
      if (DENSITY_KEYS.has(key) && !byDensity) continue;
      if (differsFromCatalogue(field.differs, have, value)) conflicts.push(field.words);
    }
    for (const [key, value] of Object.entries(patch)) {
      if (value === undefined || key === 'name' || key === 'overrideMass') continue;
      if (key === 'presetManufacturer' || key === 'presetPartNo') {
        node[key] = value;
        continue;
      }
      if (isCanopy && (key === 'cd' || key === 'spillHoleDiameter')) {
        if (!takePair) continue;
        node[key] = value;
        filled.add(wordsFor(node.type, key));
        continue;
      }
      // A hollow row's `filled: false` is the default an unset node already
      // flies, so there is nothing to fill — and "took solid from the
      // catalogue" would be a false note.
      if (key === 'filled' && value === false) continue;
      if (stated(key) === undefined) {
        node[key] = value;
        filled.add(wordsFor(node.type, key));
      }
    }
    linked += 1;
    if (conflicts.length) conflictLines.push(`${node.name ?? node.type}: ${[...new Set(conflicts)].join(', ')}`);
    const took = filled.size ? ` — took ${[...filled].join(', ')} from the catalogue` : '';
    // Said out loud, because a silently missing Cd is how the 0.8 default gets
    // blamed on the catalogue instead of on the pairing rule.
    const declined = canopyStatesHalf && patch['cd'] !== undefined
      ? ' — left the catalogue’s drag coefficient and spill hole out: this file already'
        + ' states one of the pair, and the two are one number together'
      : '';
    lines.push(`${node.name ?? node.type} → ${p.manufacturer} ${p.partNo}${took}${declined}`);
  }
  // One line per part matched in a foreign file; none from a file this app wrote.
  if (lines.length > 0) {
    notes.push(
      `${lines.length} part${lines.length === 1 ? '' : 's'} matched the parts catalogue by manufacturer and part number. `
      + `The file's own values stand; the catalogue filled in only what the file left unset: ${lines.join('; ')}.`,
    );
    // Said once, after the match sentence, and only when there is something to
    // say. It names the parts and the fields so a reader can go and look, and
    // it says what was kept — the file — so nobody reads it as a change.
    if (conflictLines.length) {
      const n = conflictLines.length;
      notes.push(
        `${n} of ${n === 1 ? 'those parts states' : 'those parts state'} a value that disagrees with `
        + `${n === 1 ? 'its' : 'their'} catalogue row — the file's value was kept: ${conflictLines.join('; ')}.`,
      );
    }
  }
  return linked;
}
