// @vitest-environment happy-dom
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { browserXmlParser } from './xmlParse.js';
import { jsXmlParser } from './xmlParseJs.js';
import { HOSTILE, runHostile, type HostileOutcome } from './xmlParseParity.js';

/**
 * Malformed, hostile and edge-case XML (xmlParseParity.ts HOSTILE), held to
 * what REAL CHROME made of each row (`__fixtures__/xml-parity/chrome-golden.json`,
 * regenerated by packages/app/scripts/xml-chrome-golden.mjs). Headless step 2,
 * 2026-10-01; spec §4 and critique F1, F4, F5.
 */
const here = dirname(fileURLToPath(import.meta.url));
const golden = JSON.parse(readFileSync(join(here, '__fixtures__/xml-parity/chrome-golden.json'), 'utf8')) as {
  chrome: string; hostile: Record<string, HostileOutcome>;
};

/**
 * Where the JS parser answers differently from Chrome ON PURPOSE. Every row
 * not named here must agree exactly; every row named here must differ, and
 * in the stated direction — so a difference that appears, or one that quietly
 * goes away, fails this test.
 */
const JS_DIFFERS_FROM_CHROME: Readonly<Record<string, string>> = {
  // A DOCTYPE: the JS parser refuses ANY (xmlParseJs.ts, piece 1). Chrome
  // accepts one, and EXPANDS internal entities from it, which no JS parser
  // does: refusing is the only answer that is never silently different. The
  // browser keeps Chrome's behaviour (ruling (b), 2026-10-01).
  bareDoctype: 'DOCTYPE refused by the JS parser',
  publicDoctypeNoSubset: 'DOCTYPE refused by the JS parser',
  doctypeInternalEntity: 'DOCTYPE refused by the JS parser (Chrome reads "EXPANDED")',
  externalEntity: 'DOCTYPE refused by the JS parser (Chrome reads it empty: not fetched)',
  dtdAfter4k: 'DOCTYPE refused by the JS parser, 5 KB into the file',
  dtdGtInSystemId: 'DOCTYPE refused by the JS parser, a ">" inside its SYSTEM id',
  // XML 1.1: Chrome reads the document as 1.0 anyway; the JS parser refuses
  // it, because saxes would apply 1.1's rules (`&#1;` legal).
  version11Plain: 'XML 1.1 declaration refused by the JS parser',
  // Nesting: Chrome refuses somewhere between 4,000 and 5,000 levels. The JS
  // parser has NO depth cap (ruling (c)): that belongs to the future server
  // package, before the parser runs.
  deep5000: 'Chrome refuses 5,000 levels of nesting; the JS parser has no cap (server package)',
};

/**
 * Where happy-dom — the browser stand-in every other test runs under — answers
 * differently from Chrome. Named so that a test that passes under happy-dom is
 * not mistaken for one that passes in a browser. The spec counted 10 of its
 * first 29; the extra rows here add 24 more.
 *
 * A SUBSET CHECK, NOT AN EXACT ONE (verify-step2 finding 9, 2026-10-01). A new
 * difference fails the test: happy-dom is the stand-in every importer test
 * trusts, so a happy-dom bump that starts disagreeing with Chrome somewhere
 * new must be read. A row happy-dom has started to AGREE on does not: the
 * monthly grouped Dependabot PR is merged when green (.github/dependabot.yml),
 * and a stand-in that got closer to the browser is no reason to stop it. The
 * test prints such a row so the list can be trimmed. The JS parser's own list
 * above stays EXACT: that parser is the one a server will ship.
 */
const HAPPY_DOM_DIFFERS_FROM_CHROME = [
  // accepts what Chrome refuses
  'undefinedEntity', 'bareAmp', 'dupAttr', 'rawCtrlChar', 'textAfterRoot', 'xml11CtrlRef', 'nulRef', 'surrogateRef',
  'loneSurrogate', 'uFFFE', 'cdataEndInText', 'doubleHyphenComment', 'digitName', 'xmlnsRebindXml', 'colonStartName',
  'version20',
  // refuses what Chrome accepts
  'cdata', 'cdataWithAmp', 'singleQuotedDecl', 'doctypeInternalEntity', 'externalEntity', 'dtdAfter4k', 'dtdGtInSystemId',
  // reads it differently
  'crlfText', 'newlineAttr',
  // overflows its own stack (Chrome refuses)
  'deep5000',
].sort();

const differing = (got: Record<string, HostileOutcome>) =>
  Object.keys(HOSTILE).filter((k) => JSON.stringify(got[k]) !== JSON.stringify(golden.hostile[k])).sort();

describe(`hostile XML, against Chrome ${golden.chrome}`, () => {
  it('the golden has an answer for every row, and no answer for a row that is gone', () => {
    expect(Object.keys(golden.hostile).sort()).toEqual(Object.keys(HOSTILE).sort());
  });

  it('the JS parser agrees with Chrome on every row but the named ones', () => {
    // When this fails after a saxes, @xmldom/xmldom or css-select bump (the
    // monthly Dependabot group carries them): the bump moved a row. Read which
    // one and why — it is a statement about what a server would now accept —
    // before changing JS_DIFFERS_FROM_CHROME or holding the package back.
    const got = runHostile(jsXmlParser);
    const unexpected = differing(got).filter((k) => !(k in JS_DIFFERS_FROM_CHROME))
      .map((k) => `${k}: Chrome ${JSON.stringify(golden.hostile[k])}, JS ${JSON.stringify(got[k])}`);
    expect(unexpected, 'a row the JS parser now answers differently from Chrome').toEqual([]);
    expect(differing(got), 'JS_DIFFERS_FROM_CHROME names a row the JS parser now agrees on').toEqual(
      Object.keys(JS_DIFFERS_FROM_CHROME).sort());
  });

  it('each named difference goes the stated way: the JS parser refuses, except the depth it does not cap', () => {
    const got = runHostile(jsXmlParser);
    for (const k of Object.keys(JS_DIFFERS_FROM_CHROME)) {
      if (k === 'deep5000') {
        expect(golden.hostile[k]).toBe('REFUSED');
        expect(got[k]).toMatchObject({ root: 'a' });
      } else {
        expect(golden.hostile[k], k).not.toBe('REFUSED');
        expect(got[k], k).toBe('REFUSED');
      }
    }
  });

  it('happy-dom differs from Chrome only on the rows named as its known gaps', () => {
    const differs = differing(runHostile(browserXmlParser));
    const fixed = HAPPY_DOM_DIFFERS_FROM_CHROME.filter((k) => !differs.includes(k));
    if (fixed.length) {
      console.warn(`happy-dom now agrees with Chrome on ${fixed.join(', ')}: `
        + 'trim HAPPY_DOM_DIFFERS_FROM_CHROME in xmlParse.hostile.test.ts.');
    }
    expect(differs.filter((k) => !HAPPY_DOM_DIFFERS_FROM_CHROME.includes(k)),
      'happy-dom now differs from Chrome on a row not named as a known gap: read it before adding it').toEqual([]);
  });

  it('entity and non-ASCII rows are READ, not merely accepted (critique F1 fix 3)', () => {
    // Spelled out, not only compared to the golden: a golden regenerated from a
    // broken browser would otherwise carry the defect with it.
    const got = runHostile(jsXmlParser);
    expect(got['entitiesInText']).toEqual({ root: 'a', txt: '&<>"\'', x: null });
    expect(got['entitiesInAttr']).toEqual({ root: 'a', txt: '', x: '&<>"\'' });
    expect(got['numericRefsText']).toEqual({ root: 'a', txt: 'éé🚀', x: null });
    expect(got['numericRefsAttr']).toEqual({ root: 'a', txt: '', x: 'éé🚀' });
    expect(got['nonAsciiName']).toEqual({ root: 'Größe', txt: 't', x: '1' });
    expect(got['nonAsciiTextAndAttr']).toEqual({ root: 'a', txt: 'é — 🚀', x: 'ü ñ 中文' });
    expect(got['replacementChar']).toEqual({ root: 'a', txt: 't�', x: '�' });
  });
});
