import { createElement, useEffect, useId, useMemo, useRef, useState, type ReactNode } from 'react';
import type { ComponentNode, RocketTree, StaticInfo } from '@online-openrocket/engine';
import { arrowPan, releasedDuring, startsGesture, wheelNotches } from '../chartPanZoom.js';
import {
  layoutSchematic, RULER_LEFT, RULER_TOP, schematicFrame, type SchematicShape, type ShapePart,
} from '../tree/schematicLayout.js';
import { PAN_SLOP, useAxialDrag } from '../hooks/useAxialDrag.js';
import {
  downloadImage, IMAGE_FORMAT_EXT, schematicSvg, svgToImage, type ExportData,
} from '../services/schematicExport.js';
import { safeName } from '../services/fileName.js';
import { ImageExportMenu } from './ImageExportMenu.js';
import { ROLL_BAR, ROLL_COL, RollControl } from './RollControl.js';
import { usePrefs } from '../prefs/PrefsContext.js';
import { uiToSi } from '../prefs/units.js';
import { rulerLayout } from '../services/rulerTicks.js';
import {
  formatStability, hasAerodynamicForce, shownCp, shownStability, stabilityState,
  type StabilityState,
} from '../services/simReport.js';
import { stabilityReadout } from './stabilityWording.js';
import { clickable as keyActivation } from './clickable.js';

/**
 * 2D side view generated by walking the component tree. Symmetric top-level
 * components (nose/transition/body) form the axial chain; children draw on
 * or inside their parent at their resolved axial position and can be DRAGGED
 * axially (snapping to structural anchors — tube ends, sibling edges).
 * Clustered inner tubes draw one outline per cluster position.
 * CG/CP markers use standard rocketry symbols.
 *
 * The walk itself — every shape's geometry — is `tree/schematicLayout.ts`,
 * pure and tested apart from this component; the axial drag is
 * `hooks/useAxialDrag.ts` (audit 2026-09-22). What is left here is the
 * drawing's state (size, zoom, pan, hover, roll), the handlers, and the
 * decoration drawn over the layout: CG/CP markers, callouts, rulers.
 */

// The ruler gutters are the layout's (it sizes the drawing around them);
// re-exported here for the views that sit beside this one and have to agree
// with it (StatTiles, the stats chip), with the centreline rule its tests pin.
export { centrelineY, RULER_LEFT, RULER_TOP } from '../tree/schematicLayout.js';

// Which press may start a drag or pan, and a release this view never saw:
// `startsGesture` / `releasedDuring` (chartPanZoom.ts), one rule shared with the
// aft view and the fin-point editor.

const MARKER_R = 9;

/** Lane-center distance from the airframe edge (or marker edge, if wider). */
const LANE_GAP = 13;
/** CP label footprint in the lower lane, relative to cpX: dot (r 4) plus
 *  the "CP" text to its right — the margin text must not land on it. */
const CP_LABEL_L = 6;
const CP_LABEL_R = 27;
/** Rough half-width of the margin text (13 px bold ≈ 7.2 px per char). */
const marginHalfW = (text: string) => (text.length * 7.2) / 2;

/** Colour is the THIRD carrier of the verdict here; the glyph and the word
 *  come from components/stabilityWording.ts, shared with the 3D callout. */
const STABILITY_VAR: Record<StabilityState, string> = {
  under: 'var(--status-serious)', over: 'var(--status-warn)', ok: 'var(--status-good)',
};

export interface CalloutLayout {
  cg: { x: number; leaderY1: number; leaderY2: number } | null;
  cp: { x: number; leaderY1: number; leaderY2: number } | null;
  margin: { x: number; y: number } | null;
}

/**
 * Leader-line callout geometry (S2): dashed leaders run from the centerline
 * markers to labeled dots in clear lanes above (CG) and below (CP) the drawn
 * airframe; the margin text sits in the LOWER lane midway between the two —
 * the upper-right corner belongs to the export/zoom control strip, which the
 * text collided with the moment the canvas became the hero (batch 08-21c) —
 * clamped inside the viewBox and nudged off the CP label when they'd collide
 * (leftward as the fallback when the right side has no room).
 *
 * @param halfPx drawn vertical half-extent (viewBox px) = vHalf * scale
 * @param top    first usable y — the horizontal ruler's gutter, 0 without one
 * @param left   first usable x — the vertical ruler's gutter, 0 without one
 */
export function calloutLayout(
  cgX: number | null, cpX: number | null,
  cy: number, halfPx: number, w: number, h: number,
  marginText: string | null, top = 0, left = 0,
): CalloutLayout {
  const laneTop = Math.max(top + 10, cy - Math.max(halfPx, MARKER_R) - LANE_GAP);
  const laneBottom = Math.min(h - 10, cy + Math.max(halfPx, MARKER_R) + LANE_GAP);
  const cg = cgX === null ? null : { x: cgX, leaderY1: cy - MARKER_R, leaderY2: laneTop };
  const cp = cpX === null ? null : { x: cpX, leaderY1: cy + MARKER_R, leaderY2: laneBottom };
  let margin: { x: number; y: number } | null = null;
  if (marginText !== null && cgX !== null && cpX !== null) {
    const halfW = marginHalfW(marginText);
    const clamp = (x: number) => Math.min(w - halfW - 2, Math.max(left + halfW + 2, x));
    const collides = (x: number) => x + halfW > cpX - CP_LABEL_L && x - halfW < cpX + CP_LABEL_R;
    let x = clamp((cgX + cpX) / 2);
    if (collides(x)) {
      const right = clamp(cpX + CP_LABEL_R + halfW);
      x = collides(right) ? clamp(cpX - CP_LABEL_L - halfW) : right;
    }
    margin = { x, y: laneBottom };
  }
  return { cg, cp, margin };
}

export function TreeSchematic({ tree, info, motors, onPatchNode, maxHeight = 480, selectedId, onSelect, exportData, onError, vertical, fillHeight, onNaturalHeight, topReserve = 0, roll: rollProp, onRoll }: {
  tree: RocketTree;
  info: StaticInfo | null;
  /** Loaded motor case dimensions (m) keyed by mount node id — drawn to
   *  scale; `label` is the designation printed in the case when it fits (S5). */
  motors?: Record<string, { length: number; diameter: number; label?: string }>;
  onPatchNode?: (id: string, patch: Partial<ComponentNode>) => void;
  /** Cap on the drawing's on-screen height (px). */
  maxHeight?: number;
  /** Two-way selection sync with the component tree (2026-08-05b #21). */
  selectedId?: string | null;
  onSelect?: (id: string) => void;
  /** When set, ⬇ SVG / ⬇ PNG export buttons appear (issue 2026-08-11a). */
  exportData?: Omit<ExportData, 'spanM'>;
  /**
   * Reports an export failure to the caller's note channel. Rasterising really
   * can fail — svgToImage rejects from img.onerror, and a big rocket at 7680px
   * can exhaust the canvas — and the awaited rejection used to go nowhere: the
   * button just did nothing, which reads as "the export is broken" with
   * nothing to report.
   */
  onError?: (message: string) => void;
  /** Nose-up view (S1 rotate / S4 phone): the horizontal layout rotates as
   *  one group to fit the container's HEIGHT. Read-mostly — drag, pan, zoom
   *  and the export/zoom controls are off; hover and click-select stay. */
  vertical?: boolean;
  /** Hero canvas (batch 08-21e): the drawing surface spans the container's
   *  FULL height instead of the adaptive content height — otherwise the svg's
   *  invisible clip edges sit mid-canvas and a zoomed rocket "slides under"
   *  what reads as a black box. Ignored in vertical mode (which fills by its
   *  own rule); overrides maxHeight. */
  fillHeight?: boolean;
  /**
   * v0.076 fit-to-content: reports the drawing's NATURAL height (px) — the
   * rocket's cross extent at width-fit scale plus padding and callout lanes,
   * uncapped — so the hero stage can size to the rocket instead of the
   * window. Only fires in fillHeight horizontal mode. Depends on container
   * WIDTH and geometry, never on container height or zoom, so it cannot
   * feed the measure→draw→grow loop the styles.css note warns about.
   */
  onNaturalHeight?: (px: number) => void;
  /**
   * Sky to keep ABOVE the drawing, in px, for whatever the host floats there —
   * for the hero canvas, the stats chip.
   *
   * The host already asks for this space by adding it to the container height
   * (App's HERO_CHIP_RESERVE), but the drawing is vertically CENTRED, so half
   * of every reserve landed below the rocket where nothing needed it. This
   * spends it where it was meant to go, and only out of slack that exists: the
   * rocket is never pushed down into its own bottom callout lane, so a
   * height-fitted drawing is untouched.
   *
   * Defaults to 0 — every caller but the hero canvas draws exactly as before.
   */
  topReserve?: number;
  /**
   * Roll about the rocket's long axis (rad), the desktop's rotation slider.
   * Optional and CONTROLLED-OR-NOT: pass both to share one angle with the Aft
   * view (App does), pass neither and the view keeps its own. Zero = the
   * design's own clock angles, so an uncontrolled instance draws exactly what
   * it drew before the slider existed.
   */
  roll?: number;
  onRoll?: (rad: number) => void;
}) {
  const { prefs, setPrefs } = usePrefs();
  // Namespaces this instance's clipPath ids. Two schematics share a document
  // on the Motors tab (this one and the Aft view), and `url(#id)` resolves to
  // the FIRST match in the document — an unqualified id would have one view
  // clipping its fins to the other's airframe.
  const uid = useId().replace(/:/g, '');
  const svgRef = useRef<SVGSVGElement>(null);
  const wrapRef = useRef<HTMLDivElement>(null);
  // Container width (CSS px). The viewBox adopts it 1:1, so the drawing fills
  // the column at native pixel scale on any monitor instead of a fixed 640px
  // canvas stretched to fit.
  const [cw, setCw] = useState(640);
  // Container height (CSS px) — the length axis in vertical mode. Stays at
  // the fallback when the wrap has no definite height to inherit.
  const [chPx, setChPx] = useState(480);
  // Hovered component (S5): accent wash + name tag drawn topmost. Enter/
  // leave never fire from touch, so phones skip hover naturally.
  const [hoverId, setHoverId] = useState<string | null>(null);
  // View transform (zoom & pan) in viewBox px; identity = whole rocket fits.
  const [zoom, setZoom] = useState({ k: 1, x: 0, y: 0 });
  // Roll, when the caller doesn't own it. See the `roll` prop.
  const [rollLocal, setRollLocal] = useState(0);
  const roll = rollProp ?? rollLocal;
  const setRoll = onRoll ?? setRollLocal;
  // `active` only becomes true once the pointer has travelled past PAN_SLOP —
  // see beginPan for why a press must not pan until then. `captured` is the
  // element the pan took the pointer for, set at that same moment (null while
  // it is only armed and holds no capture of its own) — see onLostCapture.
  const pan = useRef<{
    pointerX: number; pointerY: number; x0: number; y0: number; active: boolean; pointerId: number;
    captured: Element | null;
  } | null>(null);

  /**
   * Dimensional rulers (@atestani, 26 Aug: "Scales as in OpenRocket like the
   * top and left side"). Off in ⟳90° mode: that drawing is one rigid rotation
   * of this layout, so a ruler would come out running down the right-hand
   * side with sideways numbers. Absent preference = ON, like the desktop,
   * where the rulers are not optional at all.
   */
  const rulersPref = prefs.rulers2d ?? true;
  const rulers = !vertical && rulersPref;
  // The roll slider's column (⟳90°: its bar across the bottom). Both are
  // surrendered by the DRAWING — schematicFrame fits the rocket to what is
  // left, and every pointer↔model conversion is unaffected, because they move
  // the origin without touching the scale.
  const rollW = vertical ? 0 : ROLL_COL;
  const rollBar = vertical ? ROLL_BAR : 0;
  const hasInfo = !!info;
  // From the COMMITTED design, not the drag preview: the frame reads lengths
  // and radii, never a position, so the two give the same frame — and the
  // drag needs the frame's scale before it can say where the part is.
  const frame = useMemo(() => schematicFrame(tree, {
    cw, chPx, vertical, fillHeight, maxHeight, rulers, rollW, rollBar, lanes: hasInfo, topReserve,
  }), [tree, cw, chPx, vertical, fillHeight, maxHeight, rulers, rollW, rollBar, hasInfo, topReserve]);
  const { w, h, gutX, gutY, scale, vHalf, naturalH } = frame;
  const ctx = { scale, cy: frame.cy, x0: frame.x0 };

  // Report the natural height to the hero stage (fit-to-content, v0.076).
  // Callback identity rides a ref so a new inline closure per parent render
  // doesn't re-fire the effect; the effect keys on the VALUE.
  const onNaturalHeightRef = useRef(onNaturalHeight);
  onNaturalHeightRef.current = onNaturalHeight;
  useEffect(() => {
    if (vertical || !fillHeight) return;
    onNaturalHeightRef.current?.(naturalH);
  }, [naturalH, vertical, fillHeight]);

  // The axial drag, and the design to DRAW while one is live — the part at
  // the pointer, committed once on release (hooks/useAxialDrag.ts).
  const axial = useAxialDrag({ tree, onPatchNode, svgRef, viewWidth: w, pxPerMetre: scale * zoom.k });

  /**
   * Clears the "this press became a drag" latch at the START of every press.
   * Attached in the CAPTURE phase on the svg so it runs whatever was pressed,
   * and in vertical mode too. It used to be cleared only inside beginDrag,
   * which is attached to draggable CHILDREN alone — so once any drag passed
   * the 4 px threshold the flag stayed set, and the axial chain (nose cone,
   * body tube, transition) has no pointerdown handler of its own to clear it.
   * Clicking those became a permanent no-op while children kept working.
   */
  const resetDragLatch = axial.resetLatch;

  /**
   * Arms a background pan — but does NOT start one, and deliberately does not
   * capture the pointer yet.
   *
   * This handler runs for every press that reaches the svg, which is every
   * press on the axial chain (nose cone, body tube, transition): only
   * draggable CHILDREN stopPropagation (useAxialDrag's begin). It used to pan
   * on the very first pointermove and capture the pointer immediately, so the
   * 1-3 px of jitter in an ordinary physical click dragged the whole drawing
   * out from under the pointer between press and release. The click then
   * landed on the <svg> instead of the shape and selecting those parts did
   * nothing at all — while children stayed fine, and the vertical view (which
   * attaches neither handler) worked perfectly. Capturing on press made it
   * worse by retargeting the release as well.
   *
   * Both now wait for real movement, so a click stays a click.
   */
  const beginPan = (e: React.PointerEvent) => {
    if (!startsGesture(e)) return;
    const rect = svgRef.current?.getBoundingClientRect();
    if (!rect || rect.width === 0) return;
    pan.current = {
      pointerX: e.clientX, pointerY: e.clientY, x0: zoom.x, y0: zoom.y, active: false,
      pointerId: e.pointerId, captured: null,
    };
  };

  const onMove = (e: React.PointerEvent) => {
    // A live axial drag owns the move — every pointer's, not just its own, so
    // a second finger cannot pan the drawing out from under it.
    const dragged = axial.move(e);
    if (dragged === 'released') { endDrag(e); return; }
    if (dragged === 'busy') return;
    const p = pan.current;
    if (p) {
      if (e.pointerId !== p.pointerId) return;
      if (releasedDuring(e)) { endDrag(e); return; }
      const dx = e.clientX - p.pointerX;
      const dy = e.clientY - p.pointerY;
      // Below the slop this press is still a click, not a pan. Once it IS a
      // pan, take the pointer so the gesture survives leaving the svg.
      if (!p.active) {
        if (Math.abs(dx) < PAN_SLOP && Math.abs(dy) < PAN_SLOP) return;
        p.active = true;
        p.captured = e.currentTarget as Element;
        p.captured.setPointerCapture?.(e.pointerId);
      }
      const rect = svgRef.current?.getBoundingClientRect();
      if (!rect || rect.width === 0) return;
      const clientScale = w / rect.width;
      setZoom((z) => ({ ...z, x: p.x0 + dx * clientScale, y: p.y0 + dy * clientScale }));
    }
  };

  /** Ends the gesture its OWN pointer started — a second finger lifting (or
   *  leaving, or being cancelled) must not end the first finger's drag. */
  const endDrag = (e: React.PointerEvent) => {
    axial.end(e);
    if (pan.current?.pointerId === e.pointerId) pan.current = null;
  };

  /**
   * A lost capture ends a gesture only when it is the capture THAT gesture
   * took. On touch the browser captures the pointer implicitly to whatever was
   * pressed; the pan takes it for the svg only once it passes the slop (see
   * beginPan for why not on press), which moves it off the pressed shape — and
   * the browser fires lostpointercapture from that shape, bubbling up to here.
   * The first cut of this handler was endDrag itself, which ended the pan on
   * it: a touch pan that started on the nose, a tube or a ruler froze after
   * its first step, and once zoomed in that is nearly every touch pan
   * (reproduced in Chrome with CDP touch input, review of audit 2026-09-22).
   * An armed pan holds no capture of its own, so nothing here can end it.
   */
  const onLostCapture = (e: React.PointerEvent) => {
    axial.lostCapture(e);
    const p = pan.current;
    if (p?.pointerId === e.pointerId && p.captured && e.target === p.captured) pan.current = null;
  };

  // Track the container's size so the viewBox can follow it (height feeds
  // the vertical mode's length axis).
  useEffect(() => {
    const el = wrapRef.current;
    if (!el) return;
    const obs = new ResizeObserver(() => {
      if (el.clientWidth > 0) setCw(el.clientWidth);
      if (el.clientHeight > 0) setChPx(el.clientHeight);
    });
    obs.observe(el);
    return () => obs.disconnect();
  }, []);

  // The zoom as last committed, for the wheel listener below, which has to
  // know BEFORE it updates whether this notch zooms at all. Written in an
  // effect, not in render — a render-time ref write is undefined under
  // StrictMode's double render (the same rule AftView's eRef follows).
  const zoomRef = useRef(zoom);
  useEffect(() => { zoomRef.current = zoom; }, [zoom]);

  // Wheel zoom around the pointer. Native listener: React's onWheel is
  // passive, so preventDefault (to stop page scroll) must be attached here.
  useEffect(() => {
    const svg = svgRef.current;
    if (!svg || vertical) return;
    const onWheel = (e: WheelEvent) => {
      const rect = svg.getBoundingClientRect();
      if (rect.width === 0) return;
      // Normalised per wheel NOTCH, not per event: a high-resolution wheel
      // fires several events per detent and used to zoom several times as
      // far for the same turn of the hand. Same helper as the charts, so one
      // detent means the same thing on every view.
      const stepK = (k0: number) => Math.min(12, Math.max(1, k0 * 1.2 ** wheelNotches(e)));
      // Swallow the wheel only when it zooms (audit 2026-09-22). This used to
      // preventDefault unconditionally, so at either stop — wheel-out at fit,
      // wheel-in at 12x — the page could not scroll with the pointer over the
      // drawing, which on the Motors tab is most of the page. The charts
      // already hand a no-op wheel back the same way.
      if (stepK(zoomRef.current.k) === zoomRef.current.k) return;
      e.preventDefault();
      const px = ((e.clientX - rect.left) / rect.width) * w;
      const py = ((e.clientY - rect.top) / rect.height) * h;
      setZoom((z) => {
        const k = stepK(z.k);
        if (k === z.k) return z;
        // Keep the model point under the cursor fixed while scaling.
        const mx = (px - z.x) / z.k;
        const my = (py - z.y) / z.k;
        const next = { k, x: px - mx * k, y: py - my * k };
        return k === 1 ? { k: 1, x: 0, y: 0 } : next;
      });
    };
    svg.addEventListener('wheel', onWheel, { passive: false });
    return () => svg.removeEventListener('wheel', onWheel);
  }, [w, h, vertical]);

  // Button zoom steps around the DRAWING's center (the wheel handles precise
  // pointer-anchored zoom; these make the capability visible). Not the
  // canvas's center: once the rulers and the roll column take their gutters
  // the two are 28 px and 9 px apart, and anchoring on the canvas slid the
  // rocket down and right by that much on every step — 99 px low by the k=12
  // cap.
  const zoomBy = (f: number) => setZoom((z) => {
    const k = Math.min(12, Math.max(1, z.k * f));
    if (k === z.k) return z;
    const ax = (gutX + w) / 2;
    const ay = (gutY + h) / 2;
    const mx = (ax - z.x) / z.k;
    const my = (ay - z.y) / z.k;
    return k === 1 ? { k: 1, x: 0, y: 0 } : { k, x: ax - mx * k, y: ay - my * k };
  });

  /**
   * Arrow keys pan the drawing a tenth of its size a press, the keyboard twin
   * of the background drag (audit 2026-09-22). The buttons above zoom about the
   * centre, so once zoomed a keyboard user could Tab onto a part — the nose, the
   * fin can — that was out of sight, with no way to bring it back. Handled on
   * the svg, so the arrows work from the focused drawing AND from a focused
   * part (whose own keys are Enter and Space). Like the drag, it pans at any
   * zoom; the Fit button then appears to put it back.
   */
  const onKeyPan = (e: React.KeyboardEvent) => {
    const d = arrowPan(e.key);
    if (!d) return;
    e.preventDefault();
    setZoom((z) => ({ ...z, x: z.x + d[0] * 0.1 * w, y: z.y + d[1] * 0.1 * h }));
  };

  // Nose-up rendering rotates the whole drawing; every text label counter-
  // rotates about its own anchor so it still reads horizontally.
  const textUp = (x: number, y: number) =>
    (vertical ? { transform: `rotate(-90 ${x} ${y})` } : {});

  // --- the layout: every shape, as data (tree/schematicLayout.ts) ---
  // Memoised on what moves geometry. Selection and hover are NOT inputs: they
  // restyle what is already placed (below), so a hover no longer re-walks the
  // whole rocket once per component the pointer crosses. During a drag it is
  // the PREVIEW that is laid out, once per move that changes the part's
  // offset — a walk of the design, never a kernel rebuild.
  const shown = axial.shown;
  const layout = useMemo(() => layoutSchematic(shown, {
    scale, cy: frame.cy, x0: frame.x0, roll, motors, vertical, idPrefix: uid,
  }), [shown, scale, frame.cy, frame.x0, roll, motors, vertical, uid]);

  /**
   * The pointer and keyboard half of one drawn shape: what makes it a hover,
   * selection and (for a child part) drag target.
   *
   * The keyboard half — a tab stop, `role="button"`, a name, Enter/Space from
   * the project's shared clickable() (components/clickable.ts) — goes on ONE
   * shape per part (`stop`), not one per drawn instance (audit 2026-09-22). A
   * fin set draws a shape per fin, a cluster a rect per tube, a rail button
   * one per line instance, a pod ring its whole chain once per instance — and
   * each of them carried the part's tab stop, so Tab stepped through "Select
   * Trapezoidal fins" three times running (8 stops for 5 components,
   * measured). The stop goes on each part's first shape in paint order (which
   * is tab order) that the layout actually placed, so a fin hidden inside the
   * airframe cannot take it; every instance keeps the pointer.
   *
   * `role="button"` + a name: a bare tabbable <rect> announces nothing. The
   * pointer path keeps its own onClick because it must stopPropagation (or the
   * svg's background handler also fires) and must ignore a click that was
   * really a drag.
   */
  const interaction = (part: ShapePart, stop: boolean): Record<string, unknown> => {
    const out: Record<string, unknown> = {
      onPointerEnter: () => setHoverId(part.id),
      onPointerLeave: () => setHoverId((cur) => (cur === part.id ? null : cur)),
    };
    if (onSelect) {
      if (stop) {
        Object.assign(out, {
          onKeyDown: keyActivation(() => onSelect(part.id)).onKeyDown,
          tabIndex: 0,
          role: 'button',
          'aria-label': `Select ${part.name}`,
        });
      }
      out['onClick'] = (e: React.MouseEvent) => {
        e.stopPropagation();
        if (!axial.moved()) onSelect(part.id);
      };
      out['style'] = { cursor: 'pointer' };
    }
    const grip = part.grip ? layout.grips.get(part.id) : undefined;
    if (grip && onPatchNode && !vertical) {
      out['onPointerDown'] = (e: React.PointerEvent) => axial.begin(grip, e);
      out['style'] = { cursor: 'grab' };
    }
    return out;
  };

  /** One layout shape as an element; selection restyles its stroke. */
  const element = (s: SchematicShape, stop: boolean): ReactNode => {
    const props: Record<string, unknown> = { key: s.key, ...s.attrs };
    if (s.sel && !!selectedId && s.part?.id === selectedId) {
      props['stroke'] = 'var(--accent)';
      props['strokeWidth'] = 2;
    }
    if (s.part) Object.assign(props, interaction(s.part, stop));
    const children: ReactNode[] = [];
    if (s.title !== undefined) children.push(createElement('title', { key: 'title' }, s.title));
    for (const c of s.children ?? []) children.push(createElement(c.tag, { key: c.key, ...c.attrs }));
    if (s.text !== undefined) children.push(s.text);
    return createElement(s.tag, props, ...children);
  };
  const stops = new Set<string>();
  const drawn = layout.shapes.map((s) => {
    const stop = !!onSelect && !!s.part && !s.part.hit && !stops.has(s.part.id);
    if (stop) stops.add(s.part!.id);
    return element(s, stop);
  });
  // FAR is any distance that certainly covers the drawing in local user
  // space; the clip lives inside the view transform, so it scales with it.
  const FAR = 1e4;
  const clipDefs = layout.clips.map(({ id, top, bottom }) => (
    <clipPath key={id} id={id}>
      <rect x={-FAR} y={-FAR} width={2 * FAR} height={FAR + top} />
      <rect x={-FAR} y={bottom} width={2 * FAR} height={FAR} />
    </clipPath>
  ));

  const aero = !!info && hasAerodynamicForce(info);
  const cgX = info ? ctx.x0 + info.cg * scale : null;
  // No aerodynamic normal force = no CP, only the kernel's 0: drawn, that was a
  // red CP marker and callout at the front of a bare body tube — a violently
  // unstable-looking rocket beside tiles saying "no lift yet" (audit
  // 2026-09-22). The margin text already needed the force; now the CP does too.
  const cpX = info && aero ? ctx.x0 + shownCp(info) * scale : null;
  const stab = info && aero ? stabilityState(shownStability(info)) : null;
  // One builder for both views — components/stabilityWording.ts. The 3D
  // callout printed the bare number until v0.105, so the whole verdict rode on
  // colour there while this view spelled it out.
  const marginText = info && stab
    ? stabilityReadout(stab, formatStability(info, prefs.stabilityUnit))
    : null;
  const callouts = calloutLayout(cgX, cpX, ctx.cy, vHalf * scale, w, h, marginText, gutY, gutX);

  /**
   * The ruler gutters: a horizontal scale along the top reading axial
   * distance from the nose tip, and a vertical one down the left reading
   * distance from the centreline, both in the Preferences length unit. The
   * tick ladder is the desktop's own (services/rulerTicks).
   *
   * `view` is a zoom/pan state, not necessarily the live one — the export
   * needs the same rulers drawn for the identity view, since it always shows
   * the whole rocket whatever the screen is zoomed to.
   */
  const lenUnit = prefs.units.length;
  const pxPerUnit = scale * uiToSi('length', lenUnit, 1);
  const rulerGutters = (view: { k: number; x: number; y: number }, forExport: boolean) => {
    const across = rulerLayout(view.x + view.k * ctx.x0, view.k * pxPerUnit, gutX, w, RULER_TOP);
    const down = rulerLayout(view.y + view.k * ctx.cy, -view.k * pxPerUnit, gutY, h, RULER_LEFT);
    const band = 'var(--surface-2)';
    const edge = 'var(--border)';
    const ink = 'var(--text-secondary)';
    return (
      <g key={forExport ? 'ruler-fit' : 'ruler-view'}
        data-ruler={forExport ? 'fit' : 'view'} display={forExport ? 'none' : undefined}
        pointerEvents="none" fontSize="9" fill={ink}>
        <rect x={rollW} y={0} width={w - rollW} height={RULER_TOP} fill={band} />
        <rect x={rollW} y={0} width={RULER_LEFT} height={h} fill={band} />
        <path d={`M ${rollW} ${RULER_TOP} H ${w} M ${gutX} 0 V ${h}`} stroke={edge} strokeWidth="1" fill="none" />
        {across.map((t, i) => (
          <g key={`h${i}`}>
            <line x1={t.px} y1={RULER_TOP - t.len} x2={t.px} y2={RULER_TOP} stroke={ink} strokeWidth="1" />
            {t.label !== null && (
              <text x={t.px + 1.5} y={RULER_TOP - t.len - 2} fontWeight={t.bold ? 700 : 400}>{t.label}</text>
            )}
          </g>
        ))}
        {down.map((t, i) => (
          <g key={`v${i}`}>
            <line x1={gutX - t.len} y1={t.px} x2={gutX} y2={t.px} stroke={ink} strokeWidth="1" />
            {t.label !== null && (
              <text x={rollW + 1.5} y={t.px - 2} fontWeight={t.bold ? 700 : 400}>{t.label}</text>
            )}
          </g>
        ))}
        {/* The desktop parks a unit selector in this corner; ours only reports
            the unit, because it is the Preferences length unit and changing it
            here would silently change it everywhere else. */}
        <rect x={rollW} y={0} width={RULER_LEFT} height={RULER_TOP} fill={band} />
        <path d={`M ${gutX} 0 V ${RULER_TOP} H ${rollW}`} stroke={edge} strokeWidth="1" fill="none" />
        <text x={rollW + RULER_LEFT / 2} y={RULER_TOP / 2} textAnchor="middle" dominantBaseline="central"
          fontWeight={600}>{lenUnit}</text>
      </g>
    );
  };
  const viewIsFit = zoom.k === 1 && zoom.x === 0 && zoom.y === 0;

  // Hover overlay (S5): a light accent wash over the hovered component's
  // extent plus a name tag — deliberately fainter than the solid width-2
  // selection outline so the two stay distinguishable. The extent is the
  // union of every instance the layout drew (cluster copies, pod rings).
  const hovered = hoverId ? layout.extents.get(hoverId) : undefined;
  const hoverBox = hovered ? { x0: hovered.x0, y0: hovered.y0, x1: hovered.x1, y1: hovered.y1 } : null;
  const hoverName = hovered?.name ?? '';
  let hoverTag: { x: number; y: number; tw: number } | null = null;
  if (hoverBox) {
    const tw = hoverName.length * 6.2 + 14;
    hoverTag = {
      x: Math.min(w - tw / 2 - 2, Math.max(gutX + tw / 2 + 2, (hoverBox.x0 + hoverBox.x1) / 2)),
      // Above the component unless that leaves the drawing area (the ruler
      // gutter is not drawing area); then below.
      y: hoverBox.y0 - 22 >= gutY + 2 ? hoverBox.y0 - 13 : Math.min(h - 11, hoverBox.y1 + 13),
      tw,
    };
  }

  return (
    <div ref={wrapRef} style={{ position: 'relative', ...(vertical || fillHeight ? { height: '100%' } : null) }}>
      <svg ref={svgRef} viewBox={vertical ? `0 0 ${h} ${w}` : `0 0 ${w} ${h}`}
          style={vertical
            ? { height: '100%', maxWidth: '100%', display: 'block', margin: '0 auto' }
            : { width: '100%', height: 'auto', display: 'block', touchAction: 'none',
              cursor: zoom.k > 1 ? 'grab' : undefined }}
          // role="img" makes the WHOLE subtree presentational, so the shapes'
          // tab stops and <title>s were hidden from assistive tech — while
          // this very label promised a reader they could select and drag
          // components here. So it is an image only when there is nothing
          // inside to reach: a nose-up drawing with no onSelect (the Fly
          // screen's). Anything with tab stops is a group, whose children are
          // exposed. Until audit 2026-09-22 every vertical drawing was an
          // image, and two of them had tab stops inside it that no screen
          // reader could see: the Design tab's ⟳90° view, which really does
          // select, and the Fly screen, which passed a no-op onSelect and so
          // cost a keyboard user one dead stop per drawn part.
          role={vertical && !onSelect ? 'img' : 'group'}
          aria-label={vertical
            ? `Rocket side view, nose up, with CG and CP markers${onSelect ? ' — select components' : ''}`
            : 'Rocket side view with CG and CP markers — drag components, wheel to zoom, drag the background or use the arrow keys to pan'}
          // A tab stop of its own for the arrow-key pan (see onKeyPan) — the
          // nose-up drawing neither pans nor zooms, so it takes no keys.
          tabIndex={vertical ? undefined : 0}
          onKeyDown={vertical ? undefined : onKeyPan}
          onPointerDownCapture={resetDragLatch}
          onPointerDown={vertical ? undefined : beginPan}
          onPointerMove={vertical ? undefined : onMove}
          onPointerUp={vertical ? undefined : endDrag}
          onPointerLeave={vertical ? undefined : endDrag}
          // A gesture the browser takes over ends here rather than living on
          // to be driven by whatever pointer moves next (audit 2026-09-22) —
          // a lost capture only when it is the gesture's own (onLostCapture).
          onPointerCancel={vertical ? undefined : endDrag}
          onLostPointerCapture={vertical ? undefined : onLostCapture}>
        <defs>
          {/* Bulkhead fill: the engineering-drawing diagonal hatch. */}
          <pattern id="bulkhead-hatch" patternUnits="userSpaceOnUse" width="5" height="5">
            <path d="M0 5 L5 0" stroke="#66748c" strokeWidth="0.9" />
          </pattern>
          {clipDefs}
        </defs>
        {/* Vertical: one rigid rotation of the horizontal layout — the w×h
            layout rect maps exactly onto the transposed h×w viewBox with the
            nose (layout left) up. rotate(-90) would put it nose DOWN. */}
        <g transform={vertical
          ? `rotate(90 ${h / 2} ${h / 2})`
          : `translate(${zoom.x} ${zoom.y}) scale(${zoom.k})`}>
          {drawn}
          {/* pointerEvents none on BOTH marker groups: they are decoration
              drawn on the centreline — precisely where you click to select a
              nose cone or body tube — and an 18px opaque disc with no handler
              of its own silently ate the click. Same rule the callout group
              below already follows. */}
          {cgX !== null && (
            <g pointerEvents="none">
              <circle cx={cgX} cy={ctx.cy} r={MARKER_R} fill="var(--surface-1)" stroke="var(--text-primary)" strokeWidth="1.5" />
              <path d={`M ${cgX} ${ctx.cy} L ${cgX + MARKER_R} ${ctx.cy} A ${MARKER_R} ${MARKER_R} 0 0 1 ${cgX} ${ctx.cy + MARKER_R} Z`} fill="var(--text-primary)" />
              <path d={`M ${cgX} ${ctx.cy} L ${cgX - MARKER_R} ${ctx.cy} A ${MARKER_R} ${MARKER_R} 0 0 1 ${cgX} ${ctx.cy - MARKER_R} Z`} fill="var(--text-primary)" />
            </g>
          )}
          {cpX !== null && (
            <g pointerEvents="none">
              <circle cx={cpX} cy={ctx.cy} r={MARKER_R} fill="none" stroke="var(--status-serious)" strokeWidth="2" />
              <circle cx={cpX} cy={ctx.cy} r={3.5} fill="var(--status-serious)" />
            </g>
          )}
          {(callouts.cg || callouts.cp) && (
            <g pointerEvents="none">
              {callouts.cg && (
                <>
                  <line x1={callouts.cg.x} y1={callouts.cg.leaderY1} x2={callouts.cg.x} y2={callouts.cg.leaderY2}
                    stroke="var(--text-primary)" strokeWidth="1" strokeDasharray="4 3" />
                  <circle cx={callouts.cg.x} cy={callouts.cg.leaderY2} r={4} fill="var(--text-primary)" />
                  <text x={callouts.cg.x + 8} y={callouts.cg.leaderY2} dominantBaseline="central"
                    fontSize="11" fontWeight="bold" fill="var(--text-primary)"
                    {...textUp(callouts.cg.x + 8, callouts.cg.leaderY2)}>CG</text>
                </>
              )}
              {callouts.cp && (
                <>
                  <line x1={callouts.cp.x} y1={callouts.cp.leaderY1} x2={callouts.cp.x} y2={callouts.cp.leaderY2}
                    stroke="var(--status-serious)" strokeWidth="1" strokeDasharray="4 3" />
                  <circle cx={callouts.cp.x} cy={callouts.cp.leaderY2} r={4} fill="var(--status-serious)" />
                  <text x={callouts.cp.x + 8} y={callouts.cp.leaderY2} dominantBaseline="central"
                    fontSize="11" fontWeight="bold" fill="var(--status-serious)"
                    {...textUp(callouts.cp.x + 8, callouts.cp.leaderY2)}>CP</text>
                </>
              )}
              {callouts.margin && stab && (
                <text x={callouts.margin.x} y={callouts.margin.y} textAnchor="middle" dominantBaseline="central"
                  fontSize="13" fontWeight="bold" fill={STABILITY_VAR[stab]}
                  {...textUp(callouts.margin.x, callouts.margin.y)}>{marginText}</text>
              )}
            </g>
          )}
          {hoverBox && hoverTag && (
            <g pointerEvents="none">
              <rect x={hoverBox.x0 - 2} y={hoverBox.y0 - 2}
                width={hoverBox.x1 - hoverBox.x0 + 4} height={hoverBox.y1 - hoverBox.y0 + 4}
                rx="3" fill="var(--accent)" fillOpacity="0.14"
                stroke="var(--accent)" strokeWidth="1" strokeOpacity="0.6" />
              <g {...textUp(hoverTag.x, hoverTag.y)}>
                <rect x={hoverTag.x - hoverTag.tw / 2} y={hoverTag.y - 9}
                  width={hoverTag.tw} height={18} rx="4"
                  fill="rgba(13,14,18,0.9)" stroke="var(--border)" strokeWidth="1" />
                <text x={hoverTag.x} y={hoverTag.y} textAnchor="middle" dominantBaseline="central"
                  fontSize="11" fill="#ffffff">{hoverName}</text>
              </g>
            </g>
          )}
        </g>
        {/* Rulers ride OUTSIDE the zoom group — the gutters stay pinned to the
            canvas edge while the ticks track pan and zoom. That is also why
            the export needs a second copy: schematicSvg resets the view group
            to identity, which it cannot do to tick positions already baked in
            px, so a fit-view copy travels along hidden and is swapped in. */}
        {rulers && rulerGutters(zoom, false)}
        {rulers && !viewIsFit && rulerGutters({ k: 1, x: 0, y: 0 }, true)}
      </svg>
      {/* ⟳90° keeps the roll control — laid out along the bottom, tracking
          the axis the rocket is not drawn along — but no other controls. */}
      <RollControl roll={roll} onRoll={setRoll} top={gutY}
        orientation={vertical ? 'horizontal' : 'vertical'} />
      {/* Vertical is read-mostly: no zoom to fit-reset, and the SVG/image
          exports assume the horizontal drawing (identity view transform), so
          the whole strip hides rather than export a sideways page. */}
      {!vertical && <div className="schematic-controls" style={gutY ? { top: gutY + 6 } : undefined}>
        {exportData && (
          <>
            <button className="file-btn"
              title="True-scale 2D drawing (SVG) with design data — physical mm size, prints at 100% scale"
              onClick={() => {
                if (!svgRef.current) return;
                try {
                  const data = { ...exportData, spanM: 2 * vHalf };
                  // safeName, not an inline copy of its regex: the copy had no
                  // fallback, so a design named in Cyrillic saved "_-2d.svg"
                  // (audit 2026-09-22).
                  downloadImage(schematicSvg(svgRef.current, scale, w, h, data),
                    `${safeName(data.name)}-2d.svg`);
                } catch (e) {
                  onError?.(`SVG export failed: ${e instanceof Error ? e.message : String(e)}`);
                }
              }}>
              ⬇ SVG
            </button>
            <ImageExportMenu label="⬇ Image"
              title="High-resolution 2D image with design data — pick PNG or JPG and a width"
              onPick={async (format, widthPx) => {
                if (!svgRef.current) return;
                try {
                  const data = { ...exportData, spanM: 2 * vHalf };
                  const svg = schematicSvg(svgRef.current, scale, w, h, data);
                  downloadImage(await svgToImage(svg, widthPx, format),
                    `${safeName(data.name)}-2d.${IMAGE_FORMAT_EXT[format]}`);
                } catch (e) {
                  onError?.(`Image export failed: ${e instanceof Error ? e.message : String(e)}`
                    + ' — try a smaller width, or use ⬇ SVG.');
                }
              }} />
          </>
        )}
        <button className="file-btn"
          title={rulers ? 'Hide the dimensional rulers' : 'Show dimensional rulers along the top and left'}
          aria-label={rulers ? 'Hide rulers' : 'Show rulers'} aria-pressed={rulers}
          onClick={() => setPrefs({ ...prefs, rulers2d: !rulersPref })}>📏</button>
        {(zoom.k > 1 || zoom.x !== 0 || zoom.y !== 0) && (
          <button className="file-btn"
            title="Fit the whole rocket in view"
            onClick={() => setZoom({ k: 1, x: 0, y: 0 })}>
            ⤢ Fit
          </button>
        )}
        <button className="file-btn" title="Zoom in — or scroll on the drawing; drag it, or use the arrow keys, to pan"
          aria-label="Zoom in" onClick={() => zoomBy(1.5)} disabled={zoom.k >= 12}>+</button>
        <button className="file-btn" title="Zoom out"
          aria-label="Zoom out" onClick={() => zoomBy(1 / 1.5)} disabled={zoom.k <= 1}>−</button>
      </div>}
    </div>
  );
}
