/**
 * Validation scoring harness — grades the JS engine against the measured
 * anchor datasets in validation/anchors.json (see
 * docs/research/validation-anchors-2026-08-03.md for provenance).
 *
 * Usage:
 *   node validation/score.mjs               # classic model (flag off) scorecard to stdout
 *   node validation/score.mjs --supersonic  # score with the supersonicAero flag ON
 *   node validation/score.mjs --strict      # exit 1 if any gate point fails
 *
 * Requires the engine to be built first (`npm run build`, or
 * `npm run build -w @online-openrocket/engine`).
 *
 * Baseline expectation (classic Extended Barrowman, pre-supersonic-build):
 * supersonic CP series FAIL on every fixture — body CP is frozen at its
 * Mach-1 value in the kernel. That failure is the point of this harness;
 * each build phase should turn rows green without breaking the others.
 */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const { OrkRocket, resetEngine } = await import(
  pathToFileURL(join(here, '..', 'packages', 'engine', 'dist', 'index.js')).href
);

const anchors = JSON.parse(readFileSync(join(here, 'anchors.json'), 'utf8'));
const strict = process.argv.includes('--strict');
const supersonic = process.argv.includes('--supersonic');

/** Linear interpolation of series y over grid xs at x (clamped to range). */
function interp(xs, ys, x) {
  if (x <= xs[0]) return ys[0];
  if (x >= xs[xs.length - 1]) return ys[ys.length - 1];
  let i = 1;
  while (xs[i] < x) i++;
  const t = (x - xs[i - 1]) / (xs[i] - xs[i - 1]);
  return ys[i - 1] + t * (ys[i] - ys[i - 1]);
}

const DEG_PER_RAD = 57.29577951308232;
let gateTotal = 0;
let gatePass = 0;
const out = [];
out.push(`# Anchor scorecard — ${supersonic ? 'SUPERSONIC AERO model (flag on)' : 'classic Extended Barrowman (flag off)'}`);
out.push('');
out.push(`Generated by validation/score.mjs. Quantities: cd = drag coefficient (base included/excluded per series), cpPctL = CP as % of body length from nose, cpOverL = CP/length, cnaPerRad / cnaPerDeg = normal-force slope. gate=false rows are informational.`);
out.push('');
// Read in isolation these tables look like a tool failing its own tests — a
// reading a beta tester posted publicly on 2026-08-22. Every scorecard now
// says what a FAIL is, and against what, on its own first screen.
out.push('> **How to read this.** A row compares the model against a *measured*');
out.push('> wind-tunnel or free-flight datapoint, and FAIL means it lands outside');
out.push("> that dataset's own stated reading accuracy — a deliberately unforgiving");
out.push('> bar, and one no Barrowman-class method clears through the transonic');
out.push('> drag spike (M 0.95–1.2), where most failures cluster. These are NOT');
out.push('> comparisons against desktop OpenRocket: with the classic model this');
out.push('> engine is bit-identical to the desktop (see engine-java difftest).');
out.push("> For scale, that classic model — desktop OpenRocket's exact physics —");
out.push('> scores **7/135** on these same anchors; the supersonic model scores');
out.push('> **64/135**. Improving that number is the point of the harness.');
out.push('> Tolerances come from the datasets and are NEVER widened to make a');
out.push('> phase pass (see README).');
out.push('');

for (const [name, spec] of Object.entries(anchors)) {
  if (name.startsWith('_')) continue;
  resetEngine();
  const tree = JSON.parse(readFileSync(join(here, 'fixtures', spec.fixture), 'utf8'));
  const rocket = OrkRocket.buildTree(tree);
  if (supersonic) rocket.setSupersonicAero(true);
  const info = rocket.staticInfo();
  const sweep = rocket.dragSweep({
    machMin: 0.05, machMax: spec.maxMach ?? 10, machStep: 0.025,
    aoaDeg: spec.aoaDeg ?? 0, machAlt: spec.machAlt,
  });
  const scale = spec.refAreaScale ?? 1;

  out.push(`## ${name} — ${tree.name}`);
  out.push('');
  out.push(`Length ${info.length.toFixed(4)} m, kernel ref diameter ${info.refDiameter.toFixed(4)} m, dataset ref-area scale x${scale}.`);
  out.push('');

  const model = (series, mach) => {
    switch (series.quantity) {
      case 'cd': {
        let cd = interp(sweep.machs, sweep.powerOff.total, mach);
        if (series.base === 'excluded') cd -= interp(sweep.machs, sweep.powerOff.base, mach);
        return cd * scale;
      }
      case 'cpPctL':
        return (interp(sweep.machs, sweep.cp, mach) / info.length) * 100;
      case 'cpOverL':
        return interp(sweep.machs, sweep.cp, mach) / info.length;
      case 'cnaPerRad':
        return interp(sweep.machs, sweep.cna, mach) * scale;
      case 'cnaPerDeg':
        return (interp(sweep.machs, sweep.cna, mach) * scale) / DEG_PER_RAD;
      default:
        throw new Error(`unknown quantity ${series.quantity}`);
    }
  };

  for (const series of spec.series) {
    out.push(`### ${series.id} (${series.quantity}${series.base ? `, base ${series.base}` : ''})`);
    out.push('');
    out.push(`_${series.source}_`);
    out.push('');
    out.push('| Mach | anchor | model | delta | tol | result |');
    out.push('|---|---|---|---|---|---|');
    for (const [mach, anchor] of series.points) {
      const m = model(series, mach);
      const tol = series.relTol != null ? Math.abs(anchor) * series.relTol : series.tol;
      const delta = m - anchor;
      const inTol = Math.abs(delta) <= tol;
      const gated = series.gate
        && (series.gateMaxMach == null || mach <= series.gateMaxMach)
        && (series.gateMinMach == null || mach >= series.gateMinMach);
      if (gated) {
        gateTotal++;
        if (inTol) gatePass++;
      }
      const result = gated ? (inTol ? 'PASS' : '**FAIL**') : (inTol ? 'ok (info)' : 'off (info)');
      out.push(`| ${mach} | ${anchor} | ${m.toFixed(4)} | ${delta >= 0 ? '+' : ''}${delta.toFixed(4)} | ±${tol.toFixed(4)} | ${result} |`);
    }
    out.push('');
  }
}

out.push('## Summary');
out.push('');
out.push(`**Gate points: ${gatePass}/${gateTotal} within tolerance** (${((100 * gatePass) / gateTotal).toFixed(1)}%). Informational rows excluded.`);
out.push('');
console.log(out.join('\n'));

if (strict && gatePass < gateTotal) process.exit(1);
